/**
 * YÊU CẦU CẦN ĐẠT môn Toán — Chương trình GDPT 2018 (ban hành kèm Thông tư 32/2018/TT-BGDĐT).
 *
 * Lời văn giữ đúng Chương trình (văn bản pháp quy, dùng chung mọi trường). Một vài mục gộp nhiều bài được TÁCH theo
 * bài SGK để chẩn đoán chính xác hơn (vd lớp 10: "Thực hiện được các phép toán trên vectơ…" tách tổng–hiệu / tích với
 * một số / tích vô hướng; "hoán vị… bằng máy tính cầm tay. Khai triển nhị thức Newton…" tách hai ý).
 * `sgk` chỉ là bài tương ứng trong bộ Kết nối tri thức — để giáo viên tra, KHÔNG chép chữ của sách.
 *
 * `id` là KHOÁ ỔN ĐỊNH (đã lưu trong báo cáo) — không đổi số; thêm mục mới thì thêm id mới ở cuối khối.
 * Module thuần, không import gì — máy chủ (api/) dùng được.
 */

export type YccdStrand = 'Đại số' | 'Hình học và Đo lường' | 'Thống kê và Xác suất';

export interface YccdItem {
  id: string;
  strand: YccdStrand;
  /** Chủ đề nội dung — dùng làm nhóm khi hiện báo cáo. */
  topic: string;
  /** Bài tương ứng trong SGK Kết nối tri thức. */
  sgk: string;
  text: string;
}

const G10: readonly YccdItem[] = [
  { id: 'T10.01', strand: 'Đại số', topic: 'Mệnh đề', sgk: 'Bài 1', text: 'Thiết lập và phát biểu được các mệnh đề toán học, bao gồm: mệnh đề phủ định; mệnh đề đảo; mệnh đề tương đương; mệnh đề có chứa kí hiệu ∀, ∃; điều kiện cần, điều kiện đủ, điều kiện cần và đủ.' },
  { id: 'T10.02', strand: 'Đại số', topic: 'Mệnh đề', sgk: 'Bài 1', text: 'Xác định được tính đúng/sai của một mệnh đề toán học trong những trường hợp đơn giản.' },
  { id: 'T10.03', strand: 'Đại số', topic: 'Tập hợp và các phép toán trên tập hợp', sgk: 'Bài 2', text: 'Nhận biết được các khái niệm cơ bản về tập hợp (tập con, hai tập hợp bằng nhau, tập rỗng) và biết sử dụng các kí hiệu ⊂, ⊃, ∅.' },
  { id: 'T10.04', strand: 'Đại số', topic: 'Tập hợp và các phép toán trên tập hợp', sgk: 'Bài 2', text: 'Thực hiện được phép toán trên các tập hợp (hợp, giao, hiệu của hai tập hợp, phần bù của một tập con) và biết dùng biểu đồ Ven để biểu diễn chúng trong những trường hợp cụ thể.' },
  { id: 'T10.05', strand: 'Đại số', topic: 'Tập hợp và các phép toán trên tập hợp', sgk: 'Bài 2', text: 'Giải quyết được một số vấn đề thực tiễn gắn với phép toán trên tập hợp (ví dụ: những bài toán liên quan đến đếm số phần tử của hợp các tập hợp,...).' },
  { id: 'T10.06', strand: 'Đại số', topic: 'Bất phương trình, hệ bất phương trình bậc nhất hai ẩn', sgk: 'Bài 3–4', text: 'Nhận biết được bất phương trình và hệ bất phương trình bậc nhất hai ẩn.' },
  { id: 'T10.07', strand: 'Đại số', topic: 'Bất phương trình, hệ bất phương trình bậc nhất hai ẩn', sgk: 'Bài 3–4', text: 'Biểu diễn được miền nghiệm của bất phương trình và hệ bất phương trình bậc nhất hai ẩn trên mặt phẳng toạ độ.' },
  { id: 'T10.08', strand: 'Đại số', topic: 'Bất phương trình, hệ bất phương trình bậc nhất hai ẩn', sgk: 'Bài 3–4', text: 'Vận dụng được kiến thức về bất phương trình, hệ bất phương trình bậc nhất hai ẩn vào giải quyết bài toán thực tiễn (ví dụ: bài toán tìm cực trị của biểu thức F = ax + by trên một miền đa giác,...).' },
  { id: 'T10.09', strand: 'Đại số', topic: 'Hàm số và đồ thị', sgk: 'Bài 15', text: 'Nhận biết được những mô hình thực tế (dạng bảng, biểu đồ, công thức) dẫn đến khái niệm hàm số.' },
  { id: 'T10.10', strand: 'Đại số', topic: 'Hàm số và đồ thị', sgk: 'Bài 15', text: 'Mô tả được các khái niệm cơ bản về hàm số: định nghĩa hàm số, tập xác định, tập giá trị, hàm số đồng biến, hàm số nghịch biến, đồ thị của hàm số.' },
  { id: 'T10.11', strand: 'Đại số', topic: 'Hàm số và đồ thị', sgk: 'Bài 15', text: 'Mô tả được các đặc trưng hình học của đồ thị hàm số đồng biến, hàm số nghịch biến.' },
  { id: 'T10.12', strand: 'Đại số', topic: 'Hàm số và đồ thị', sgk: 'Bài 15', text: 'Vận dụng được kiến thức của hàm số vào giải quyết bài toán thực tiễn (ví dụ: xây dựng hàm số bậc nhất trên những khoảng khác nhau để tính số tiền y (phải trả) theo số phút gọi x đối với một gói cước điện thoại,...).' },
  { id: 'T10.13', strand: 'Đại số', topic: 'Hàm số bậc hai', sgk: 'Bài 16', text: 'Thiết lập được bảng giá trị của hàm số bậc hai.' },
  { id: 'T10.14', strand: 'Đại số', topic: 'Hàm số bậc hai', sgk: 'Bài 16', text: 'Vẽ được Parabola (parabol) là đồ thị hàm số bậc hai.' },
  { id: 'T10.15', strand: 'Đại số', topic: 'Hàm số bậc hai', sgk: 'Bài 16', text: 'Nhận biết được các tính chất cơ bản của Parabola như đỉnh, trục đối xứng.' },
  { id: 'T10.16', strand: 'Đại số', topic: 'Hàm số bậc hai', sgk: 'Bài 16', text: 'Nhận biết và giải thích được các tính chất của hàm số bậc hai thông qua đồ thị.' },
  { id: 'T10.17', strand: 'Đại số', topic: 'Hàm số bậc hai', sgk: 'Bài 16', text: 'Vận dụng được kiến thức về hàm số bậc hai và đồ thị vào giải quyết bài toán thực tiễn (ví dụ: xác định độ cao của cầu, cổng có hình dạng Parabola,...).' },
  { id: 'T10.18', strand: 'Đại số', topic: 'Dấu của tam thức bậc hai. Bất phương trình bậc hai một ẩn', sgk: 'Bài 17', text: 'Giải thích được định lí về dấu của tam thức bậc hai từ việc quan sát đồ thị của hàm bậc hai.' },
  { id: 'T10.19', strand: 'Đại số', topic: 'Dấu của tam thức bậc hai. Bất phương trình bậc hai một ẩn', sgk: 'Bài 17', text: 'Giải được bất phương trình bậc hai.' },
  { id: 'T10.20', strand: 'Đại số', topic: 'Dấu của tam thức bậc hai. Bất phương trình bậc hai một ẩn', sgk: 'Bài 17', text: 'Vận dụng được bất phương trình bậc hai một ẩn vào giải quyết bài toán thực tiễn (ví dụ: xác định chiều cao tối đa để xe có thể qua hầm có hình dạng Parabola,...).' },
  { id: 'T10.21', strand: 'Đại số', topic: 'Phương trình quy về phương trình bậc hai', sgk: 'Bài 18', text: 'Giải được phương trình chứa căn thức có dạng: √(ax² + bx + c) = √(dx² + ex + f); √(ax² + bx + c) = dx + e.' },
  { id: 'T10.22', strand: 'Đại số', topic: 'Quy tắc đếm, hoán vị, chỉnh hợp, tổ hợp', sgk: 'Bài 23–24', text: 'Vận dụng được quy tắc cộng và quy tắc nhân trong một số tình huống đơn giản (ví dụ: đếm số khả năng xuất hiện mặt sấp/ngửa khi tung một số đồng xu,...).' },
  { id: 'T10.23', strand: 'Đại số', topic: 'Quy tắc đếm, hoán vị, chỉnh hợp, tổ hợp', sgk: 'Bài 23–24', text: 'Vận dụng được sơ đồ hình cây trong các bài toán đếm đơn giản các đối tượng trong Toán học, trong các môn học khác cũng như trong thực tiễn (ví dụ: đếm số hợp tử tạo thành trong Sinh học, hoặc đếm số trận đấu trong một giải thể thao,...).' },
  { id: 'T10.24', strand: 'Đại số', topic: 'Quy tắc đếm, hoán vị, chỉnh hợp, tổ hợp', sgk: 'Bài 23–24', text: 'Tính được số các hoán vị, chỉnh hợp, tổ hợp.' },
  { id: 'T10.25', strand: 'Đại số', topic: 'Quy tắc đếm, hoán vị, chỉnh hợp, tổ hợp', sgk: 'Bài 23–24', text: 'Tính được số các hoán vị, chỉnh hợp, tổ hợp bằng máy tính cầm tay.' },
  { id: 'T10.26', strand: 'Đại số', topic: 'Nhị thức Newton', sgk: 'Bài 25', text: 'Khai triển được nhị thức Newton (a + b)ⁿ với số mũ thấp (n = 4 hoặc n = 5) bằng cách vận dụng tổ hợp.' },
  { id: 'T10.27', strand: 'Hình học và Đo lường', topic: 'Giá trị lượng giác của một góc từ 0° đến 180°', sgk: 'Bài 5', text: 'Nhận biết được giá trị lượng giác của một góc từ 0° đến 180°.' },
  { id: 'T10.28', strand: 'Hình học và Đo lường', topic: 'Giá trị lượng giác của một góc từ 0° đến 180°', sgk: 'Bài 5', text: 'Tính được giá trị lượng giác (đúng hoặc gần đúng) của một góc từ 0° đến 180° bằng máy tính cầm tay.' },
  { id: 'T10.29', strand: 'Hình học và Đo lường', topic: 'Giá trị lượng giác của một góc từ 0° đến 180°', sgk: 'Bài 5', text: 'Giải thích được hệ thức liên hệ giữa giá trị lượng giác của các góc phụ nhau, bù nhau.' },
  { id: 'T10.30', strand: 'Hình học và Đo lường', topic: 'Hệ thức lượng trong tam giác', sgk: 'Bài 6', text: 'Giải thích được các hệ thức lượng cơ bản trong tam giác: định lí côsin, định lí sin, công thức tính diện tích tam giác.' },
  { id: 'T10.31', strand: 'Hình học và Đo lường', topic: 'Hệ thức lượng trong tam giác', sgk: 'Bài 6', text: 'Mô tả được cách giải tam giác và vận dụng được vào việc giải một số bài toán có nội dung thực tiễn (ví dụ: xác định khoảng cách giữa hai địa điểm khi gặp vật cản, xác định chiều cao của vật khi không thể đo trực tiếp,...).' },
  { id: 'T10.32', strand: 'Hình học và Đo lường', topic: 'Vectơ: khái niệm mở đầu', sgk: 'Bài 7', text: 'Nhận biết được khái niệm vectơ, vectơ bằng nhau, vectơ-không.' },
  { id: 'T10.33', strand: 'Hình học và Đo lường', topic: 'Vectơ: khái niệm mở đầu', sgk: 'Bài 7', text: 'Biểu thị được một số đại lượng trong thực tiễn bằng vectơ.' },
  { id: 'T10.34', strand: 'Hình học và Đo lường', topic: 'Tổng và hiệu của hai vectơ', sgk: 'Bài 8', text: 'Thực hiện được phép toán tổng và hiệu hai vectơ và mô tả được những tính chất hình học (trung điểm của đoạn thẳng, trọng tâm của tam giác,...) bằng vectơ.' },
  { id: 'T10.35', strand: 'Hình học và Đo lường', topic: 'Tích của một vectơ với một số', sgk: 'Bài 9', text: 'Thực hiện được phép toán tích của một số với vectơ và mô tả được những tính chất hình học (ba điểm thẳng hàng, trung điểm của đoạn thẳng, trọng tâm của tam giác,...) bằng vectơ.' },
  { id: 'T10.36', strand: 'Hình học và Đo lường', topic: 'Tích vô hướng của hai vectơ', sgk: 'Bài 11', text: 'Thực hiện được phép toán tích vô hướng của hai vectơ.' },
  { id: 'T10.37', strand: 'Hình học và Đo lường', topic: 'Vectơ và ứng dụng', sgk: 'Bài 8–11', text: 'Sử dụng được vectơ và các phép toán trên vectơ để giải thích một số hiện tượng có liên quan đến Vật lí và Hoá học (ví dụ: những vấn đề liên quan đến lực, đến chuyển động,...).' },
  { id: 'T10.38', strand: 'Hình học và Đo lường', topic: 'Vectơ và ứng dụng', sgk: 'Bài 8–11', text: 'Vận dụng được kiến thức về vectơ để giải một số bài toán hình học và một số bài toán liên quan đến thực tiễn (ví dụ: xác định lực tác dụng lên vật,...).' },
  { id: 'T10.39', strand: 'Hình học và Đo lường', topic: 'Vectơ trong mặt phẳng toạ độ', sgk: 'Bài 10', text: 'Nhận biết được toạ độ của vectơ đối với một hệ trục toạ độ.' },
  { id: 'T10.40', strand: 'Hình học và Đo lường', topic: 'Vectơ trong mặt phẳng toạ độ', sgk: 'Bài 10', text: 'Tìm được toạ độ của một vectơ, độ dài của một vectơ khi biết toạ độ hai đầu mút của nó.' },
  { id: 'T10.41', strand: 'Hình học và Đo lường', topic: 'Vectơ trong mặt phẳng toạ độ', sgk: 'Bài 10', text: 'Sử dụng được biểu thức toạ độ của các phép toán vectơ trong tính toán.' },
  { id: 'T10.42', strand: 'Hình học và Đo lường', topic: 'Vectơ trong mặt phẳng toạ độ', sgk: 'Bài 10', text: 'Vận dụng được kiến thức về toạ độ của vectơ để giải một số bài toán liên quan đến thực tiễn (ví dụ: vị trí của vật trên mặt phẳng toạ độ,...).' },
  { id: 'T10.43', strand: 'Hình học và Đo lường', topic: 'Vectơ trong mặt phẳng toạ độ', sgk: 'Bài 11', text: 'Vận dụng được phương pháp toạ độ vào bài toán giải tam giác.' },
  { id: 'T10.44', strand: 'Hình học và Đo lường', topic: 'Phương trình đường thẳng', sgk: 'Bài 19', text: 'Mô tả được phương trình tổng quát và phương trình tham số của đường thẳng trong mặt phẳng toạ độ.' },
  { id: 'T10.45', strand: 'Hình học và Đo lường', topic: 'Phương trình đường thẳng', sgk: 'Bài 19', text: 'Thiết lập được phương trình của đường thẳng trong mặt phẳng khi biết: một điểm và một vectơ pháp tuyến; biết một điểm và một vectơ chỉ phương; biết hai điểm.' },
  { id: 'T10.46', strand: 'Hình học và Đo lường', topic: 'Phương trình đường thẳng', sgk: 'Bài 19', text: 'Giải thích được mối liên hệ giữa đồ thị hàm số bậc nhất và đường thẳng trong mặt phẳng toạ độ.' },
  { id: 'T10.47', strand: 'Hình học và Đo lường', topic: 'Vị trí tương đối, góc và khoảng cách', sgk: 'Bài 20', text: 'Nhận biết được hai đường thẳng cắt nhau, song song, trùng nhau, vuông góc với nhau bằng phương pháp toạ độ.' },
  { id: 'T10.48', strand: 'Hình học và Đo lường', topic: 'Vị trí tương đối, góc và khoảng cách', sgk: 'Bài 20', text: 'Thiết lập được công thức tính góc giữa hai đường thẳng.' },
  { id: 'T10.49', strand: 'Hình học và Đo lường', topic: 'Vị trí tương đối, góc và khoảng cách', sgk: 'Bài 20', text: 'Tính được khoảng cách từ một điểm đến một đường thẳng bằng phương pháp toạ độ.' },
  { id: 'T10.50', strand: 'Hình học và Đo lường', topic: 'Vị trí tương đối, góc và khoảng cách', sgk: 'Bài 20', text: 'Vận dụng được kiến thức về phương trình đường thẳng để giải một số bài toán có liên quan đến thực tiễn.' },
  { id: 'T10.51', strand: 'Hình học và Đo lường', topic: 'Đường tròn trong mặt phẳng toạ độ', sgk: 'Bài 21', text: 'Thiết lập được phương trình đường tròn khi biết toạ độ tâm và bán kính; biết toạ độ ba điểm mà đường tròn đi qua; xác định được tâm và bán kính đường tròn khi biết phương trình của đường tròn.' },
  { id: 'T10.52', strand: 'Hình học và Đo lường', topic: 'Đường tròn trong mặt phẳng toạ độ', sgk: 'Bài 21', text: 'Thiết lập được phương trình tiếp tuyến của đường tròn khi biết toạ độ của tiếp điểm.' },
  { id: 'T10.53', strand: 'Hình học và Đo lường', topic: 'Đường tròn trong mặt phẳng toạ độ', sgk: 'Bài 21', text: 'Vận dụng được kiến thức về phương trình đường tròn để giải một số bài toán liên quan đến thực tiễn (ví dụ: bài toán về chuyển động tròn trong Vật lí,...).' },
  { id: 'T10.54', strand: 'Hình học và Đo lường', topic: 'Ba đường conic', sgk: 'Bài 22', text: 'Nhận biết được ba đường conic bằng hình học.' },
  { id: 'T10.55', strand: 'Hình học và Đo lường', topic: 'Ba đường conic', sgk: 'Bài 22', text: 'Nhận biết được phương trình chính tắc của ba đường conic trong mặt phẳng toạ độ.' },
  { id: 'T10.56', strand: 'Hình học và Đo lường', topic: 'Ba đường conic', sgk: 'Bài 22', text: 'Giải quyết được một số vấn đề thực tiễn gắn với ba đường conic (ví dụ: giải thích một số hiện tượng trong Quang học,...).' },
  { id: 'T10.57', strand: 'Thống kê và Xác suất', topic: 'Số gần đúng và sai số', sgk: 'Bài 12', text: 'Hiểu được khái niệm số gần đúng, sai số tuyệt đối.' },
  { id: 'T10.58', strand: 'Thống kê và Xác suất', topic: 'Số gần đúng và sai số', sgk: 'Bài 12', text: 'Xác định được số gần đúng của một số với độ chính xác cho trước.' },
  { id: 'T10.59', strand: 'Thống kê và Xác suất', topic: 'Số gần đúng và sai số', sgk: 'Bài 12', text: 'Xác định được sai số tương đối của số gần đúng.' },
  { id: 'T10.60', strand: 'Thống kê và Xác suất', topic: 'Số gần đúng và sai số', sgk: 'Bài 12', text: 'Xác định được số quy tròn của số gần đúng với độ chính xác cho trước.' },
  { id: 'T10.61', strand: 'Thống kê và Xác suất', topic: 'Số gần đúng và sai số', sgk: 'Bài 12', text: 'Biết sử dụng máy tính cầm tay để tính toán với các số gần đúng.' },
  { id: 'T10.62', strand: 'Thống kê và Xác suất', topic: 'Mô tả và biểu diễn dữ liệu', sgk: 'Chương V', text: 'Phát hiện và lí giải được số liệu không chính xác dựa trên mối liên hệ toán học đơn giản giữa các số liệu đã được biểu diễn trong nhiều ví dụ.' },
  { id: 'T10.63', strand: 'Thống kê và Xác suất', topic: 'Số đặc trưng đo xu thế trung tâm', sgk: 'Bài 13', text: 'Tính được số đặc trưng đo xu thế trung tâm cho mẫu số liệu không ghép nhóm: số trung bình cộng (hay số trung bình), trung vị (median), tứ phân vị (quartiles), mốt (mode).' },
  { id: 'T10.64', strand: 'Thống kê và Xác suất', topic: 'Số đặc trưng đo xu thế trung tâm', sgk: 'Bài 13', text: 'Giải thích được ý nghĩa và vai trò của các số đặc trưng nói trên của mẫu số liệu trong thực tiễn.' },
  { id: 'T10.65', strand: 'Thống kê và Xác suất', topic: 'Số đặc trưng đo xu thế trung tâm', sgk: 'Bài 13', text: 'Chỉ ra được những kết luận nhờ ý nghĩa của số đặc trưng nói trên của mẫu số liệu trong trường hợp đơn giản.' },
  { id: 'T10.66', strand: 'Thống kê và Xác suất', topic: 'Số đặc trưng đo mức độ phân tán', sgk: 'Bài 14', text: 'Tính được số đặc trưng đo mức độ phân tán cho mẫu số liệu không ghép nhóm: khoảng biến thiên, khoảng tứ phân vị, phương sai, độ lệch chuẩn.' },
  { id: 'T10.67', strand: 'Thống kê và Xác suất', topic: 'Số đặc trưng đo mức độ phân tán', sgk: 'Bài 14', text: 'Giải thích được ý nghĩa và vai trò của các số đặc trưng nói trên của mẫu số liệu trong thực tiễn.' },
  { id: 'T10.68', strand: 'Thống kê và Xác suất', topic: 'Số đặc trưng đo mức độ phân tán', sgk: 'Bài 14', text: 'Chỉ ra được những kết luận nhờ ý nghĩa của số đặc trưng nói trên của mẫu số liệu trong trường hợp đơn giản.' },
  { id: 'T10.69', strand: 'Thống kê và Xác suất', topic: 'Số đặc trưng đo mức độ phân tán', sgk: 'Bài 14', text: 'Nhận biết được mối liên hệ giữa thống kê với những kiến thức của các môn học trong Chương trình lớp 10 và trong thực tiễn.' },
  { id: 'T10.70', strand: 'Thống kê và Xác suất', topic: 'Biến cố và định nghĩa cổ điển của xác suất', sgk: 'Bài 26', text: 'Nhận biết được một số khái niệm về xác suất cổ điển: phép thử ngẫu nhiên; không gian mẫu; biến cố (biến cố là tập con của không gian mẫu); biến cố đối; định nghĩa cổ điển của xác suất; nguyên lí xác suất bé.' },
  { id: 'T10.71', strand: 'Thống kê và Xác suất', topic: 'Biến cố và định nghĩa cổ điển của xác suất', sgk: 'Bài 26', text: 'Mô tả được không gian mẫu, biến cố trong một số thí nghiệm đơn giản (ví dụ: tung đồng xu hai lần, tung đồng xu ba lần, tung xúc xắc hai lần).' },
  { id: 'T10.72', strand: 'Thống kê và Xác suất', topic: 'Biến cố và định nghĩa cổ điển của xác suất', sgk: 'Bài 26', text: 'Mô tả được các tính chất cơ bản của xác suất.' },
  { id: 'T10.73', strand: 'Thống kê và Xác suất', topic: 'Tính xác suất theo định nghĩa cổ điển', sgk: 'Bài 27', text: 'Tính được xác suất của biến cố trong một số bài toán đơn giản bằng phương pháp tổ hợp (trường hợp xác suất phân bố đều).' },
  { id: 'T10.74', strand: 'Thống kê và Xác suất', topic: 'Tính xác suất theo định nghĩa cổ điển', sgk: 'Bài 27', text: 'Tính được xác suất trong một số thí nghiệm lặp bằng cách sử dụng sơ đồ hình cây (ví dụ: tung xúc xắc hai lần, tính xác suất để tổng số chấm xuất hiện trong hai lần tung bằng 7).' },
  { id: 'T10.75', strand: 'Thống kê và Xác suất', topic: 'Tính xác suất theo định nghĩa cổ điển', sgk: 'Bài 27', text: 'Tính được xác suất của biến cố đối.' },
];

const G11: readonly YccdItem[] = [
  { id: 'T11.01', strand: 'Đại số', topic: 'Giá trị lượng giác của góc lượng giác', sgk: 'Bài 1', text: 'Nhận biết được các khái niệm cơ bản về góc lượng giác: khái niệm góc lượng giác; số đo của góc lượng giác; hệ thức Chasles cho các góc lượng giác; đường tròn lượng giác.' },
  { id: 'T11.02', strand: 'Đại số', topic: 'Giá trị lượng giác của góc lượng giác', sgk: 'Bài 1', text: 'Nhận biết được khái niệm giá trị lượng giác của một góc lượng giác.' },
  { id: 'T11.03', strand: 'Đại số', topic: 'Giá trị lượng giác của góc lượng giác', sgk: 'Bài 1', text: 'Mô tả được bảng giá trị lượng giác của một số góc lượng giác thường gặp; hệ thức cơ bản giữa các giá trị lượng giác của một góc lượng giác; quan hệ giữa các giá trị lượng giác của các góc lượng giác có liên quan đặc biệt: bù nhau, phụ nhau, đối nhau, hơn kém nhau π.' },
  { id: 'T11.04', strand: 'Đại số', topic: 'Giá trị lượng giác của góc lượng giác', sgk: 'Bài 1', text: 'Sử dụng được máy tính cầm tay để tính giá trị lượng giác của một góc lượng giác khi biết số đo của góc đó.' },
  { id: 'T11.05', strand: 'Đại số', topic: 'Công thức lượng giác', sgk: 'Bài 2', text: 'Mô tả được các phép biến đổi lượng giác cơ bản: công thức cộng; công thức góc nhân đôi; công thức biến đổi tích thành tổng và công thức biến đổi tổng thành tích.' },
  { id: 'T11.06', strand: 'Đại số', topic: 'Giá trị lượng giác và biến đổi lượng giác: vận dụng', sgk: 'Bài 1–2', text: 'Giải quyết được một số vấn đề thực tiễn gắn với giá trị lượng giác của góc lượng giác và các phép biến đổi lượng giác.' },
  { id: 'T11.07', strand: 'Đại số', topic: 'Hàm số lượng giác', sgk: 'Bài 3', text: 'Nhận biết được các khái niệm về hàm số chẵn, hàm số lẻ, hàm số tuần hoàn.' },
  { id: 'T11.08', strand: 'Đại số', topic: 'Hàm số lượng giác', sgk: 'Bài 3', text: 'Nhận biết được các đặc trưng hình học của đồ thị hàm số chẵn, hàm số lẻ, hàm số tuần hoàn.' },
  { id: 'T11.09', strand: 'Đại số', topic: 'Hàm số lượng giác', sgk: 'Bài 3', text: 'Nhận biết được định nghĩa các hàm lượng giác y = sin x, y = cos x, y = tan x, y = cot x thông qua đường tròn lượng giác.' },
  { id: 'T11.10', strand: 'Đại số', topic: 'Hàm số lượng giác', sgk: 'Bài 3', text: 'Mô tả được bảng giá trị của bốn hàm số lượng giác đó trên một chu kì.' },
  { id: 'T11.11', strand: 'Đại số', topic: 'Hàm số lượng giác', sgk: 'Bài 3', text: 'Vẽ được đồ thị của các hàm số y = sin x, y = cos x, y = tan x, y = cot x.' },
  { id: 'T11.12', strand: 'Đại số', topic: 'Hàm số lượng giác', sgk: 'Bài 3', text: 'Giải thích được: tập xác định; tập giá trị; tính chất chẵn, lẻ; tính tuần hoàn; chu kì; khoảng đồng biến, nghịch biến của các hàm số y = sin x, y = cos x, y = tan x, y = cot x dựa vào đồ thị.' },
  { id: 'T11.13', strand: 'Đại số', topic: 'Hàm số lượng giác', sgk: 'Bài 3', text: 'Giải quyết được một số vấn đề thực tiễn gắn với hàm số lượng giác (ví dụ: một số bài toán có liên quan đến dao động điều hoà trong Vật lí,...).' },
  { id: 'T11.14', strand: 'Đại số', topic: 'Phương trình lượng giác cơ bản', sgk: 'Bài 4', text: 'Nhận biết được công thức nghiệm của phương trình lượng giác cơ bản: sin x = m; cos x = m; tan x = m; cot x = m bằng cách vận dụng đồ thị hàm số lượng giác tương ứng.' },
  { id: 'T11.15', strand: 'Đại số', topic: 'Phương trình lượng giác cơ bản', sgk: 'Bài 4', text: 'Tính được nghiệm gần đúng của phương trình lượng giác cơ bản bằng máy tính cầm tay.' },
  { id: 'T11.16', strand: 'Đại số', topic: 'Phương trình lượng giác cơ bản', sgk: 'Bài 4', text: 'Giải được phương trình lượng giác ở dạng vận dụng trực tiếp phương trình lượng giác cơ bản (ví dụ: giải phương trình lượng giác dạng sin 2x = sin 3x, sin x = cos 3x).' },
  { id: 'T11.17', strand: 'Đại số', topic: 'Phương trình lượng giác cơ bản', sgk: 'Bài 4', text: 'Giải quyết được một số vấn đề thực tiễn gắn với phương trình lượng giác (ví dụ: một số bài toán liên quan đến dao động điều hòa trong Vật lí,...).' },
  { id: 'T11.18', strand: 'Đại số', topic: 'Dãy số', sgk: 'Bài 5', text: 'Nhận biết được dãy số hữu hạn, dãy số vô hạn.' },
  { id: 'T11.19', strand: 'Đại số', topic: 'Dãy số', sgk: 'Bài 5', text: 'Thể hiện được cách cho dãy số bằng liệt kê các số hạng; bằng công thức tổng quát; bằng hệ thức truy hồi; bằng cách mô tả.' },
  { id: 'T11.20', strand: 'Đại số', topic: 'Dãy số', sgk: 'Bài 5', text: 'Nhận biết được tính chất tăng, giảm, bị chặn của dãy số trong những trường hợp đơn giản.' },
  { id: 'T11.21', strand: 'Đại số', topic: 'Cấp số cộng', sgk: 'Bài 6', text: 'Nhận biết được một dãy số là cấp số cộng.' },
  { id: 'T11.22', strand: 'Đại số', topic: 'Cấp số cộng', sgk: 'Bài 6', text: 'Giải thích được công thức xác định số hạng tổng quát của cấp số cộng.' },
  { id: 'T11.23', strand: 'Đại số', topic: 'Cấp số cộng', sgk: 'Bài 6', text: 'Tính được tổng của n số hạng đầu tiên của cấp số cộng.' },
  { id: 'T11.24', strand: 'Đại số', topic: 'Cấp số cộng', sgk: 'Bài 6', text: 'Giải quyết được một số vấn đề thực tiễn gắn với cấp số cộng để giải một số bài toán liên quan đến thực tiễn (ví dụ: một số vấn đề trong Sinh học, trong Giáo dục dân số,...).' },
  { id: 'T11.25', strand: 'Đại số', topic: 'Cấp số nhân', sgk: 'Bài 7', text: 'Nhận biết được một dãy số là cấp số nhân.' },
  { id: 'T11.26', strand: 'Đại số', topic: 'Cấp số nhân', sgk: 'Bài 7', text: 'Giải thích được công thức xác định số hạng tổng quát của cấp số nhân.' },
  { id: 'T11.27', strand: 'Đại số', topic: 'Cấp số nhân', sgk: 'Bài 7', text: 'Tính được tổng của n số hạng đầu tiên của cấp số nhân.' },
  { id: 'T11.28', strand: 'Đại số', topic: 'Cấp số nhân', sgk: 'Bài 7', text: 'Giải quyết được một số vấn đề thực tiễn gắn với cấp số nhân để giải một số bài toán liên quan đến thực tiễn (ví dụ: một số vấn đề trong Sinh học, trong Giáo dục dân số,...).' },
  { id: 'T11.29', strand: 'Đại số', topic: 'Giới hạn của dãy số', sgk: 'Bài 15', text: 'Nhận biết được khái niệm giới hạn của dãy số.' },
  { id: 'T11.30', strand: 'Đại số', topic: 'Giới hạn của dãy số', sgk: 'Bài 15', text: 'Giải thích được một số giới hạn cơ bản như: lim 1/nᵏ = 0 (k ∈ ℕ*); lim qⁿ = 0 (|q| < 1); lim c = c với c là hằng số (n → +∞).' },
  { id: 'T11.31', strand: 'Đại số', topic: 'Giới hạn của dãy số', sgk: 'Bài 15', text: 'Vận dụng được các phép toán giới hạn dãy số để tìm giới hạn của một số dãy số đơn giản (ví dụ: lim (2n + 1)/n; lim √(4n² + 1)/n).' },
  { id: 'T11.32', strand: 'Đại số', topic: 'Giới hạn của dãy số', sgk: 'Bài 15', text: 'Tính được tổng của một cấp số nhân lùi vô hạn và vận dụng được kết quả đó để giải quyết một số tình huống thực tiễn giả định hoặc liên quan đến thực tiễn.' },
  { id: 'T11.33', strand: 'Đại số', topic: 'Giới hạn của hàm số', sgk: 'Bài 16', text: 'Nhận biết được khái niệm giới hạn hữu hạn của hàm số, giới hạn hữu hạn một phía của hàm số tại một điểm.' },
  { id: 'T11.34', strand: 'Đại số', topic: 'Giới hạn của hàm số', sgk: 'Bài 16', text: 'Nhận biết được khái niệm giới hạn hữu hạn của hàm số tại vô cực và mô tả được một số giới hạn cơ bản như: lim c/xᵏ = 0 (x → +∞), lim c/xᵏ = 0 (x → −∞) với c là hằng số và k là số nguyên dương.' },
  { id: 'T11.35', strand: 'Đại số', topic: 'Giới hạn của hàm số', sgk: 'Bài 16', text: 'Nhận biết được khái niệm giới hạn vô cực (một phía) của hàm số tại một điểm và hiểu được một số giới hạn cơ bản như: lim 1/(x − a) = +∞ (x → a⁺); lim 1/(x − a) = −∞ (x → a⁻).' },
  { id: 'T11.36', strand: 'Đại số', topic: 'Giới hạn của hàm số', sgk: 'Bài 16', text: 'Tính được một số giới hạn hàm số bằng cách vận dụng các phép toán trên giới hạn hàm số.' },
  { id: 'T11.37', strand: 'Đại số', topic: 'Giới hạn của hàm số', sgk: 'Bài 16', text: 'Giải quyết được một số vấn đề thực tiễn gắn với giới hạn hàm số.' },
  { id: 'T11.38', strand: 'Đại số', topic: 'Hàm số liên tục', sgk: 'Bài 17', text: 'Nhận dạng được hàm số liên tục tại một điểm, hoặc trên một khoảng, hoặc trên một đoạn.' },
  { id: 'T11.39', strand: 'Đại số', topic: 'Hàm số liên tục', sgk: 'Bài 17', text: 'Nhận dạng được tính liên tục của tổng, hiệu, tích, thương của hai hàm số liên tục.' },
  { id: 'T11.40', strand: 'Đại số', topic: 'Hàm số liên tục', sgk: 'Bài 17', text: 'Nhận biết được tính liên tục của một số hàm sơ cấp cơ bản (như hàm đa thức, hàm phân thức, hàm căn thức, hàm lượng giác) trên tập xác định của chúng.' },
  { id: 'T11.41', strand: 'Đại số', topic: 'Luỹ thừa', sgk: 'Bài 18', text: 'Nhận biết được khái niệm luỹ thừa với số mũ nguyên của một số thực khác 0; luỹ thừa với số mũ hữu tỉ và luỹ thừa với số mũ thực của một số thực dương.' },
  { id: 'T11.42', strand: 'Đại số', topic: 'Luỹ thừa', sgk: 'Bài 18', text: 'Giải thích được các tính chất của phép tính luỹ thừa với số mũ nguyên, luỹ thừa với số mũ hữu tỉ và luỹ thừa với số mũ thực.' },
  { id: 'T11.43', strand: 'Đại số', topic: 'Luỹ thừa', sgk: 'Bài 18', text: 'Sử dụng được tính chất của phép tính luỹ thừa trong tính toán các biểu thức số và rút gọn các biểu thức chứa biến (tính viết và tính nhẩm, tính nhanh một cách hợp lí).' },
  { id: 'T11.44', strand: 'Đại số', topic: 'Luỹ thừa', sgk: 'Bài 18', text: 'Tính được giá trị biểu thức số có chứa phép tính luỹ thừa bằng sử dụng máy tính cầm tay.' },
  { id: 'T11.45', strand: 'Đại số', topic: 'Luỹ thừa', sgk: 'Bài 18', text: 'Giải quyết được một số vấn đề có liên quan đến môn học khác hoặc có liên quan đến thực tiễn gắn với phép tính luỹ thừa (ví dụ: bài toán về lãi suất, sự tăng trưởng,...).' },
  { id: 'T11.46', strand: 'Đại số', topic: 'Lôgarit', sgk: 'Bài 19', text: 'Nhận biết được khái niệm lôgarit cơ số a (a > 0, a ≠ 1) của một số thực dương.' },
  { id: 'T11.47', strand: 'Đại số', topic: 'Lôgarit', sgk: 'Bài 19', text: 'Giải thích được các tính chất của phép tính lôgarit nhờ sử dụng định nghĩa hoặc các tính chất đã biết trước đó.' },
  { id: 'T11.48', strand: 'Đại số', topic: 'Lôgarit', sgk: 'Bài 19', text: 'Sử dụng được tính chất của phép tính lôgarit trong tính toán các biểu thức số và rút gọn các biểu thức chứa biến (tính viết và tính nhẩm, tính nhanh một cách hợp lí).' },
  { id: 'T11.49', strand: 'Đại số', topic: 'Lôgarit', sgk: 'Bài 19', text: 'Tính được giá trị (đúng hoặc gần đúng) của lôgarit bằng cách sử dụng máy tính cầm tay.' },
  { id: 'T11.50', strand: 'Đại số', topic: 'Lôgarit', sgk: 'Bài 19', text: 'Giải quyết được một số vấn đề có liên quan đến môn học khác hoặc có liên quan đến thực tiễn gắn với phép tính lôgarit (ví dụ: bài toán liên quan đến độ pH trong Hoá học,...).' },
  { id: 'T11.51', strand: 'Đại số', topic: 'Hàm số mũ và hàm số lôgarit', sgk: 'Bài 20', text: 'Nhận biết được hàm số mũ và hàm số lôgarit. Nêu được một số ví dụ thực tế về hàm số mũ, hàm số lôgarit.' },
  { id: 'T11.52', strand: 'Đại số', topic: 'Hàm số mũ và hàm số lôgarit', sgk: 'Bài 20', text: 'Nhận dạng được đồ thị của các hàm số mũ, hàm số lôgarit.' },
  { id: 'T11.53', strand: 'Đại số', topic: 'Hàm số mũ và hàm số lôgarit', sgk: 'Bài 20', text: 'Giải thích được các tính chất của hàm số mũ, hàm số lôgarit thông qua đồ thị của chúng.' },
  { id: 'T11.54', strand: 'Đại số', topic: 'Hàm số mũ và hàm số lôgarit', sgk: 'Bài 20', text: 'Giải quyết được một số vấn đề có liên quan đến môn học khác hoặc có liên quan đến thực tiễn gắn với hàm số mũ và hàm số lôgarit (ví dụ: lãi suất, sự tăng trưởng,...).' },
  { id: 'T11.55', strand: 'Đại số', topic: 'Phương trình, bất phương trình mũ và lôgarit', sgk: 'Bài 21', text: 'Giải được phương trình, bất phương trình mũ, lôgarit ở dạng đơn giản (ví dụ: 2ˣ⁺¹ = 1/4; 2ˣ⁺¹ = 2³ˣ⁺⁵; log₂(x + 1) = 3; log₃(x + 1) = log₃(x² − 1)).' },
  { id: 'T11.56', strand: 'Đại số', topic: 'Phương trình, bất phương trình mũ và lôgarit', sgk: 'Bài 21', text: 'Giải quyết được một số vấn đề có liên quan đến môn học khác hoặc có liên quan đến thực tiễn gắn với phương trình, bất phương trình mũ và lôgarit (ví dụ: bài toán liên quan đến độ pH, độ rung chấn,...).' },
  { id: 'T11.57', strand: 'Đại số', topic: 'Đạo hàm', sgk: 'Bài 31–32', text: 'Nhận biết được một số bài toán dẫn đến khái niệm đạo hàm như: xác định vận tốc tức thời của một vật chuyển động không đều, xác định tốc độ thay đổi của nhiệt độ.' },
  { id: 'T11.58', strand: 'Đại số', topic: 'Đạo hàm', sgk: 'Bài 31–32', text: 'Nhận biết được định nghĩa đạo hàm. Tính được đạo hàm của một số hàm đơn giản bằng định nghĩa.' },
  { id: 'T11.59', strand: 'Đại số', topic: 'Đạo hàm', sgk: 'Bài 31–32', text: 'Nhận biết được ý nghĩa hình học của đạo hàm.' },
  { id: 'T11.60', strand: 'Đại số', topic: 'Đạo hàm', sgk: 'Bài 31–32', text: 'Thiết lập được phương trình tiếp tuyến của đồ thị hàm số tại một điểm thuộc đồ thị.' },
  { id: 'T11.61', strand: 'Đại số', topic: 'Đạo hàm', sgk: 'Bài 31–32', text: 'Nhận biết được số e thông qua bài toán mô hình hoá lãi suất ngân hàng.' },
  { id: 'T11.62', strand: 'Đại số', topic: 'Đạo hàm', sgk: 'Bài 31–32', text: 'Tính được đạo hàm của một số hàm số sơ cấp cơ bản (như hàm đa thức, hàm căn thức đơn giản, hàm số lượng giác, hàm số mũ, hàm số lôgarit).' },
  { id: 'T11.63', strand: 'Đại số', topic: 'Đạo hàm', sgk: 'Bài 31–32', text: 'Sử dụng được các công thức tính đạo hàm của tổng, hiệu, tích, thương của các hàm số và đạo hàm của hàm hợp.' },
  { id: 'T11.64', strand: 'Đại số', topic: 'Đạo hàm', sgk: 'Bài 31–32', text: 'Giải quyết được một số vấn đề có liên quan đến môn học khác hoặc có liên quan đến thực tiễn gắn với đạo hàm (ví dụ: xác định vận tốc tức thời của một vật chuyển động không đều,...).' },
  { id: 'T11.65', strand: 'Đại số', topic: 'Đạo hàm cấp hai', sgk: 'Bài 33', text: 'Nhận biết được khái niệm đạo hàm cấp hai của một hàm số.' },
  { id: 'T11.66', strand: 'Đại số', topic: 'Đạo hàm cấp hai', sgk: 'Bài 33', text: 'Tính được đạo hàm cấp hai của một số hàm số đơn giản.' },
  { id: 'T11.67', strand: 'Đại số', topic: 'Đạo hàm cấp hai', sgk: 'Bài 33', text: 'Giải quyết được một số vấn đề có liên quan đến môn học khác hoặc có liên quan đến thực tiễn gắn với đạo hàm cấp hai (ví dụ: xác định gia tốc từ đồ thị vận tốc theo thời gian của một chuyển động không đều,...).' },
  { id: 'T11.68', strand: 'Hình học và Đo lường', topic: 'Đường thẳng và mặt phẳng trong không gian', sgk: 'Bài 10', text: 'Nhận biết được các quan hệ liên thuộc cơ bản giữa điểm, đường thẳng, mặt phẳng trong không gian.' },
  { id: 'T11.69', strand: 'Hình học và Đo lường', topic: 'Đường thẳng và mặt phẳng trong không gian', sgk: 'Bài 10', text: 'Mô tả được ba cách xác định mặt phẳng (qua ba điểm không thẳng hàng; qua một đường thẳng và một điểm không thuộc đường thẳng đó; qua hai đường thẳng cắt nhau).' },
  { id: 'T11.70', strand: 'Hình học và Đo lường', topic: 'Đường thẳng và mặt phẳng trong không gian', sgk: 'Bài 10', text: 'Xác định được giao tuyến của hai mặt phẳng; giao điểm của đường thẳng và mặt phẳng.' },
  { id: 'T11.71', strand: 'Hình học và Đo lường', topic: 'Đường thẳng và mặt phẳng trong không gian', sgk: 'Bài 10', text: 'Vận dụng được các tính chất về giao tuyến của hai mặt phẳng; giao điểm của đường thẳng và mặt phẳng vào giải bài tập.' },
  { id: 'T11.72', strand: 'Hình học và Đo lường', topic: 'Đường thẳng và mặt phẳng trong không gian', sgk: 'Bài 10', text: 'Nhận biết được hình chóp, hình tứ diện.' },
  { id: 'T11.73', strand: 'Hình học và Đo lường', topic: 'Đường thẳng và mặt phẳng trong không gian', sgk: 'Bài 10', text: 'Vận dụng được kiến thức về đường thẳng, mặt phẳng trong không gian để mô tả một số hình ảnh trong thực tiễn.' },
  { id: 'T11.74', strand: 'Hình học và Đo lường', topic: 'Hai đường thẳng song song', sgk: 'Bài 11', text: 'Nhận biết được vị trí tương đối của hai đường thẳng trong không gian: hai đường thẳng trùng nhau, song song, cắt nhau, chéo nhau trong không gian.' },
  { id: 'T11.75', strand: 'Hình học và Đo lường', topic: 'Hai đường thẳng song song', sgk: 'Bài 11', text: 'Giải thích được tính chất cơ bản về hai đường thẳng song song trong không gian.' },
  { id: 'T11.76', strand: 'Hình học và Đo lường', topic: 'Hai đường thẳng song song', sgk: 'Bài 11', text: 'Vận dụng được kiến thức về hai đường thẳng song song để mô tả một số hình ảnh trong thực tiễn.' },
  { id: 'T11.77', strand: 'Hình học và Đo lường', topic: 'Đường thẳng và mặt phẳng song song', sgk: 'Bài 12', text: 'Nhận biết được đường thẳng song song với mặt phẳng.' },
  { id: 'T11.78', strand: 'Hình học và Đo lường', topic: 'Đường thẳng và mặt phẳng song song', sgk: 'Bài 12', text: 'Giải thích được điều kiện để đường thẳng song song với mặt phẳng.' },
  { id: 'T11.79', strand: 'Hình học và Đo lường', topic: 'Đường thẳng và mặt phẳng song song', sgk: 'Bài 12', text: 'Giải thích được tính chất cơ bản về đường thẳng song song với mặt phẳng.' },
  { id: 'T11.80', strand: 'Hình học và Đo lường', topic: 'Đường thẳng và mặt phẳng song song', sgk: 'Bài 12', text: 'Vận dụng được kiến thức về đường thẳng song song với mặt phẳng để mô tả một số hình ảnh trong thực tiễn.' },
  { id: 'T11.81', strand: 'Hình học và Đo lường', topic: 'Hai mặt phẳng song song', sgk: 'Bài 13', text: 'Nhận biết được hai mặt phẳng song song trong không gian.' },
  { id: 'T11.82', strand: 'Hình học và Đo lường', topic: 'Hai mặt phẳng song song', sgk: 'Bài 13', text: 'Giải thích được điều kiện để hai mặt phẳng song song.' },
  { id: 'T11.83', strand: 'Hình học và Đo lường', topic: 'Hai mặt phẳng song song', sgk: 'Bài 13', text: 'Giải thích được tính chất cơ bản về hai mặt phẳng song song.' },
  { id: 'T11.84', strand: 'Hình học và Đo lường', topic: 'Hai mặt phẳng song song', sgk: 'Bài 13', text: 'Giải thích được định lí Thalès trong không gian.' },
  { id: 'T11.85', strand: 'Hình học và Đo lường', topic: 'Hai mặt phẳng song song', sgk: 'Bài 13', text: 'Giải thích được tính chất cơ bản của lăng trụ và hình hộp.' },
  { id: 'T11.86', strand: 'Hình học và Đo lường', topic: 'Hai mặt phẳng song song', sgk: 'Bài 13', text: 'Vận dụng được kiến thức về quan hệ song song để mô tả một số hình ảnh trong thực tiễn.' },
  { id: 'T11.87', strand: 'Hình học và Đo lường', topic: 'Phép chiếu song song', sgk: 'Bài 14', text: 'Nhận biết được khái niệm và các tính chất cơ bản về phép chiếu song song.' },
  { id: 'T11.88', strand: 'Hình học và Đo lường', topic: 'Phép chiếu song song', sgk: 'Bài 14', text: 'Xác định được ảnh của một điểm, một đoạn thẳng, một tam giác, một đường tròn qua một phép chiếu song song.' },
  { id: 'T11.89', strand: 'Hình học và Đo lường', topic: 'Phép chiếu song song', sgk: 'Bài 14', text: 'Vẽ được hình biểu diễn của một số hình khối đơn giản.' },
  { id: 'T11.90', strand: 'Hình học và Đo lường', topic: 'Phép chiếu song song', sgk: 'Bài 14', text: 'Sử dụng được kiến thức về phép chiếu song song để mô tả một số hình ảnh trong thực tiễn.' },
  { id: 'T11.91', strand: 'Hình học và Đo lường', topic: 'Hai đường thẳng vuông góc', sgk: 'Bài 22', text: 'Nhận biết được khái niệm góc giữa hai đường thẳng trong không gian.' },
  { id: 'T11.92', strand: 'Hình học và Đo lường', topic: 'Hai đường thẳng vuông góc', sgk: 'Bài 22', text: 'Nhận biết được hai đường thẳng vuông góc trong không gian.' },
  { id: 'T11.93', strand: 'Hình học và Đo lường', topic: 'Hai đường thẳng vuông góc', sgk: 'Bài 22', text: 'Chứng minh được hai đường thẳng vuông góc trong không gian trong một số trường hợp đơn giản.' },
  { id: 'T11.94', strand: 'Hình học và Đo lường', topic: 'Hai đường thẳng vuông góc', sgk: 'Bài 22', text: 'Sử dụng được kiến thức về hai đường thẳng vuông góc để mô tả một số hình ảnh trong thực tiễn.' },
  { id: 'T11.95', strand: 'Hình học và Đo lường', topic: 'Đường thẳng vuông góc với mặt phẳng', sgk: 'Bài 23', text: 'Nhận biết được đường thẳng vuông góc với mặt phẳng.' },
  { id: 'T11.96', strand: 'Hình học và Đo lường', topic: 'Đường thẳng vuông góc với mặt phẳng', sgk: 'Bài 23', text: 'Xác định được điều kiện để đường thẳng vuông góc với mặt phẳng.' },
  { id: 'T11.97', strand: 'Hình học và Đo lường', topic: 'Đường thẳng vuông góc với mặt phẳng', sgk: 'Bài 23', text: 'Giải thích được định lí ba đường vuông góc.' },
  { id: 'T11.98', strand: 'Hình học và Đo lường', topic: 'Đường thẳng vuông góc với mặt phẳng', sgk: 'Bài 23', text: 'Giải thích được mối liên hệ giữa tính song song và tính vuông góc của đường thẳng và mặt phẳng.' },
  { id: 'T11.99', strand: 'Hình học và Đo lường', topic: 'Đường thẳng vuông góc với mặt phẳng', sgk: 'Bài 23', text: 'Vận dụng được kiến thức về đường thẳng vuông góc với mặt phẳng để mô tả một số hình ảnh trong thực tiễn.' },
  { id: 'T11.100', strand: 'Hình học và Đo lường', topic: 'Phép chiếu vuông góc. Góc giữa đường thẳng và mặt phẳng', sgk: 'Bài 24', text: 'Nhận biết được khái niệm phép chiếu vuông góc.' },
  { id: 'T11.101', strand: 'Hình học và Đo lường', topic: 'Phép chiếu vuông góc. Góc giữa đường thẳng và mặt phẳng', sgk: 'Bài 24', text: 'Xác định được hình chiếu vuông góc của một điểm, một đường thẳng, một tam giác.' },
  { id: 'T11.102', strand: 'Hình học và Đo lường', topic: 'Phép chiếu vuông góc. Góc giữa đường thẳng và mặt phẳng', sgk: 'Bài 24', text: 'Nhận biết được khái niệm góc giữa đường thẳng và mặt phẳng.' },
  { id: 'T11.103', strand: 'Hình học và Đo lường', topic: 'Phép chiếu vuông góc. Góc giữa đường thẳng và mặt phẳng', sgk: 'Bài 24', text: 'Xác định và tính được góc giữa đường thẳng và mặt phẳng trong những trường hợp đơn giản (ví dụ: đã biết hình chiếu vuông góc của đường thẳng lên mặt phẳng).' },
  { id: 'T11.104', strand: 'Hình học và Đo lường', topic: 'Hai mặt phẳng vuông góc. Góc nhị diện', sgk: 'Bài 25', text: 'Nhận biết được hai mặt phẳng vuông góc trong không gian.' },
  { id: 'T11.105', strand: 'Hình học và Đo lường', topic: 'Hai mặt phẳng vuông góc. Góc nhị diện', sgk: 'Bài 25', text: 'Xác định được điều kiện để hai mặt phẳng vuông góc.' },
  { id: 'T11.106', strand: 'Hình học và Đo lường', topic: 'Hai mặt phẳng vuông góc. Góc nhị diện', sgk: 'Bài 25', text: 'Giải thích được tính chất cơ bản về hai mặt phẳng vuông góc.' },
  { id: 'T11.107', strand: 'Hình học và Đo lường', topic: 'Hai mặt phẳng vuông góc. Góc nhị diện', sgk: 'Bài 25', text: 'Giải thích được tính chất cơ bản của hình lăng trụ đứng, lăng trụ đều, hình hộp đứng, hình hộp chữ nhật, hình lập phương, hình chóp đều.' },
  { id: 'T11.108', strand: 'Hình học và Đo lường', topic: 'Hai mặt phẳng vuông góc. Góc nhị diện', sgk: 'Bài 25', text: 'Vận dụng được kiến thức về hai mặt phẳng vuông góc để mô tả một số hình ảnh trong thực tiễn.' },
  { id: 'T11.109', strand: 'Hình học và Đo lường', topic: 'Hai mặt phẳng vuông góc. Góc nhị diện', sgk: 'Bài 25', text: 'Nhận biết được khái niệm góc nhị diện, góc phẳng nhị diện.' },
  { id: 'T11.110', strand: 'Hình học và Đo lường', topic: 'Hai mặt phẳng vuông góc. Góc nhị diện', sgk: 'Bài 25', text: 'Xác định và tính được số đo góc nhị diện, góc phẳng nhị diện trong những trường hợp đơn giản (ví dụ: nhận biết được mặt phẳng vuông góc với cạnh nhị diện).' },
  { id: 'T11.111', strand: 'Hình học và Đo lường', topic: 'Hai mặt phẳng vuông góc. Góc nhị diện', sgk: 'Bài 25', text: 'Sử dụng được kiến thức về góc giữa đường thẳng và mặt phẳng, góc nhị diện để mô tả một số hình ảnh trong thực tiễn.' },
  { id: 'T11.112', strand: 'Hình học và Đo lường', topic: 'Khoảng cách', sgk: 'Bài 26', text: 'Xác định được khoảng cách từ một điểm đến một đường thẳng; khoảng cách từ một điểm đến một mặt phẳng; khoảng cách giữa hai đường thẳng song song; khoảng cách giữa đường thẳng và mặt phẳng song song; khoảng cách giữa hai mặt phẳng song song trong những trường hợp đơn giản.' },
  { id: 'T11.113', strand: 'Hình học và Đo lường', topic: 'Khoảng cách', sgk: 'Bài 26', text: 'Nhận biết được đường vuông góc chung của hai đường thẳng chéo nhau; tính được khoảng cách giữa hai đường thẳng chéo nhau trong những trường hợp đơn giản (ví dụ: có một đường thẳng vuông góc với mặt phẳng chứa đường thẳng còn lại).' },
  { id: 'T11.114', strand: 'Hình học và Đo lường', topic: 'Khoảng cách', sgk: 'Bài 26', text: 'Sử dụng được kiến thức về khoảng cách trong không gian để mô tả một số hình ảnh trong thực tiễn.' },
  { id: 'T11.115', strand: 'Hình học và Đo lường', topic: 'Thể tích', sgk: 'Bài 27', text: 'Nhận biết được công thức tính thể tích của hình chóp, hình lăng trụ, hình hộp.' },
  { id: 'T11.116', strand: 'Hình học và Đo lường', topic: 'Thể tích', sgk: 'Bài 27', text: 'Tính được thể tích của hình chóp, hình lăng trụ, hình hộp trong những trường hợp đơn giản (ví dụ: nhận biết được đường cao và diện tích mặt đáy của hình chóp).' },
  { id: 'T11.117', strand: 'Hình học và Đo lường', topic: 'Thể tích', sgk: 'Bài 27', text: 'Nhận biết được hình chóp cụt đều.' },
  { id: 'T11.118', strand: 'Hình học và Đo lường', topic: 'Thể tích', sgk: 'Bài 27', text: 'Tính được thể tích khối chóp cụt đều.' },
  { id: 'T11.119', strand: 'Hình học và Đo lường', topic: 'Thể tích', sgk: 'Bài 27', text: 'Vận dụng được kiến thức về hình chóp cụt đều để mô tả một số hình ảnh trong thực tiễn.' },
  { id: 'T11.120', strand: 'Thống kê và Xác suất', topic: 'Số đặc trưng của mẫu số liệu ghép nhóm', sgk: 'Bài 8–9', text: 'Tính được các số đặc trưng đo xu thế trung tâm cho mẫu số liệu ghép nhóm: số trung bình cộng (hay số trung bình), trung vị (median), tứ phân vị (quartiles), mốt (mode).' },
  { id: 'T11.121', strand: 'Thống kê và Xác suất', topic: 'Số đặc trưng của mẫu số liệu ghép nhóm', sgk: 'Bài 8–9', text: 'Hiểu được ý nghĩa và vai trò của các số đặc trưng nói trên của mẫu số liệu trong thực tiễn.' },
  { id: 'T11.122', strand: 'Thống kê và Xác suất', topic: 'Số đặc trưng của mẫu số liệu ghép nhóm', sgk: 'Bài 8–9', text: 'Rút ra được kết luận nhờ ý nghĩa của các số đặc trưng nói trên của mẫu số liệu trong trường hợp đơn giản.' },
  { id: 'T11.123', strand: 'Thống kê và Xác suất', topic: 'Số đặc trưng của mẫu số liệu ghép nhóm', sgk: 'Bài 8–9', text: 'Nhận biết được mối liên hệ giữa thống kê với những kiến thức của các môn học khác trong Chương trình lớp 11 và trong thực tiễn.' },
  { id: 'T11.124', strand: 'Thống kê và Xác suất', topic: 'Biến cố hợp, biến cố giao, biến cố độc lập', sgk: 'Bài 28', text: 'Nhận biết được một số khái niệm về xác suất cổ điển: hợp và giao các biến cố; biến cố độc lập.' },
  { id: 'T11.125', strand: 'Thống kê và Xác suất', topic: 'Công thức cộng và công thức nhân xác suất', sgk: 'Bài 29–30', text: 'Tính được xác suất của biến cố hợp bằng cách sử dụng công thức cộng.' },
  { id: 'T11.126', strand: 'Thống kê và Xác suất', topic: 'Công thức cộng và công thức nhân xác suất', sgk: 'Bài 29–30', text: 'Tính được xác suất của biến cố giao bằng cách sử dụng công thức nhân (cho trường hợp biến cố độc lập).' },
  { id: 'T11.127', strand: 'Thống kê và Xác suất', topic: 'Công thức cộng và công thức nhân xác suất', sgk: 'Bài 29–30', text: 'Tính được xác suất của biến cố trong một số bài toán đơn giản bằng phương pháp tổ hợp.' },
  { id: 'T11.128', strand: 'Thống kê và Xác suất', topic: 'Công thức cộng và công thức nhân xác suất', sgk: 'Bài 29–30', text: 'Tính được xác suất trong một số bài toán đơn giản bằng cách sử dụng sơ đồ hình cây.' },
];

const G12: readonly YccdItem[] = [
  { id: 'T12.01', strand: 'Đại số', topic: 'Tính đơn điệu và cực trị của hàm số', sgk: 'Bài 1', text: 'Nhận biết được tính đồng biến, nghịch biến của một hàm số trên một khoảng dựa vào dấu của đạo hàm cấp một của nó.' },
  { id: 'T12.02', strand: 'Đại số', topic: 'Tính đơn điệu và cực trị của hàm số', sgk: 'Bài 1', text: 'Thể hiện được tính đồng biến, nghịch biến của hàm số trong bảng biến thiên.' },
  { id: 'T12.03', strand: 'Đại số', topic: 'Tính đơn điệu và cực trị của hàm số', sgk: 'Bài 1', text: 'Nhận biết được tính đơn điệu, điểm cực trị, giá trị cực trị của hàm số thông qua bảng biến thiên hoặc thông qua hình ảnh hình học của đồ thị hàm số.' },
  { id: 'T12.04', strand: 'Đại số', topic: 'Giá trị lớn nhất, giá trị nhỏ nhất của hàm số', sgk: 'Bài 2', text: 'Nhận biết được giá trị lớn nhất, giá trị nhỏ nhất của hàm số trên một tập xác định cho trước.' },
  { id: 'T12.05', strand: 'Đại số', topic: 'Giá trị lớn nhất, giá trị nhỏ nhất của hàm số', sgk: 'Bài 2', text: 'Xác định được giá trị lớn nhất, giá trị nhỏ nhất của hàm số bằng đạo hàm trong những trường hợp đơn giản.' },
  { id: 'T12.06', strand: 'Đại số', topic: 'Đường tiệm cận của đồ thị hàm số', sgk: 'Bài 3', text: 'Nhận biết được hình ảnh hình học của đường tiệm cận ngang, đường tiệm cận đứng, đường tiệm cận xiên của đồ thị hàm số.' },
  { id: 'T12.07', strand: 'Đại số', topic: 'Khảo sát sự biến thiên và vẽ đồ thị hàm số', sgk: 'Bài 4', text: 'Mô tả được sơ đồ tổng quát để khảo sát hàm số (tìm tập xác định, xét chiều biến thiên, tìm cực trị, tìm tiệm cận, lập bảng biến thiên, vẽ đồ thị).' },
  { id: 'T12.08', strand: 'Đại số', topic: 'Khảo sát sự biến thiên và vẽ đồ thị hàm số', sgk: 'Bài 4', text: 'Khảo sát được tập xác định, chiều biến thiên, cực trị, tiệm cận, bảng biến thiên và vẽ đồ thị của các hàm số: y = ax³ + bx² + cx + d (a ≠ 0); y = (ax + b)/(cx + d) (c ≠ 0, ad − bc ≠ 0); y = (ax² + bx + c)/(mx + n) (a ≠ 0, m ≠ 0 và đa thức tử không chia hết cho đa thức mẫu).' },
  { id: 'T12.09', strand: 'Đại số', topic: 'Khảo sát sự biến thiên và vẽ đồ thị hàm số', sgk: 'Bài 4', text: 'Nhận biết được tính đối xứng (trục đối xứng, tâm đối xứng) của đồ thị các hàm số trên.' },
  { id: 'T12.10', strand: 'Đại số', topic: 'Ứng dụng đạo hàm giải quyết vấn đề thực tiễn', sgk: 'Bài 5', text: 'Vận dụng được đạo hàm và khảo sát hàm số để giải quyết một số vấn đề liên quan đến thực tiễn.' },
  { id: 'T12.11', strand: 'Đại số', topic: 'Nguyên hàm', sgk: 'Bài 11', text: 'Nhận biết được khái niệm nguyên hàm của một hàm số.' },
  { id: 'T12.12', strand: 'Đại số', topic: 'Nguyên hàm', sgk: 'Bài 11', text: 'Giải thích được tính chất cơ bản của nguyên hàm.' },
  { id: 'T12.13', strand: 'Đại số', topic: 'Nguyên hàm', sgk: 'Bài 11', text: 'Xác định được nguyên hàm của một số hàm số sơ cấp như: y = xᵅ (α ≠ −1); y = 1/x; y = sin x; y = cos x; y = 1/cos²x; y = 1/sin²x; y = aˣ; y = eˣ.' },
  { id: 'T12.14', strand: 'Đại số', topic: 'Nguyên hàm', sgk: 'Bài 11', text: 'Tính được nguyên hàm trong những trường hợp đơn giản.' },
  { id: 'T12.15', strand: 'Đại số', topic: 'Tích phân', sgk: 'Bài 12', text: 'Nhận biết được định nghĩa và các tính chất của tích phân.' },
  { id: 'T12.16', strand: 'Đại số', topic: 'Tích phân', sgk: 'Bài 12', text: 'Tính được tích phân trong những trường hợp đơn giản.' },
  { id: 'T12.17', strand: 'Đại số', topic: 'Ứng dụng hình học của tích phân', sgk: 'Bài 13', text: 'Sử dụng được tích phân để tính diện tích của một số hình phẳng, thể tích của một số hình khối.' },
  { id: 'T12.18', strand: 'Đại số', topic: 'Ứng dụng hình học của tích phân', sgk: 'Bài 13', text: 'Vận dụng được tích phân để giải một số bài toán có liên quan đến thực tiễn.' },
  { id: 'T12.19', strand: 'Hình học và Đo lường', topic: 'Vectơ trong không gian', sgk: 'Bài 6', text: 'Nhận biết được vectơ và các phép toán vectơ trong không gian (tổng và hiệu của hai vectơ, tích của một số với một vectơ, tích vô hướng của hai vectơ).' },
  { id: 'T12.20', strand: 'Hình học và Đo lường', topic: 'Hệ trục toạ độ trong không gian', sgk: 'Bài 7', text: 'Nhận biết được toạ độ của một vectơ đối với hệ trục toạ độ.' },
  { id: 'T12.21', strand: 'Hình học và Đo lường', topic: 'Biểu thức toạ độ của các phép toán vectơ', sgk: 'Bài 8', text: 'Xác định được độ dài của một vectơ khi biết toạ độ hai đầu mút của nó và biểu thức toạ độ của các phép toán vectơ.' },
  { id: 'T12.22', strand: 'Hình học và Đo lường', topic: 'Biểu thức toạ độ của các phép toán vectơ', sgk: 'Bài 8', text: 'Xác định được biểu thức toạ độ của các phép toán vectơ.' },
  { id: 'T12.23', strand: 'Hình học và Đo lường', topic: 'Biểu thức toạ độ của các phép toán vectơ', sgk: 'Bài 8', text: 'Vận dụng được toạ độ của vectơ để giải một số bài toán có liên quan đến thực tiễn.' },
  { id: 'T12.24', strand: 'Hình học và Đo lường', topic: 'Phương trình mặt phẳng', sgk: 'Bài 14', text: 'Nhận biết được phương trình tổng quát của mặt phẳng.' },
  { id: 'T12.25', strand: 'Hình học và Đo lường', topic: 'Phương trình mặt phẳng', sgk: 'Bài 14', text: 'Thiết lập được phương trình tổng quát của mặt phẳng trong hệ trục toạ độ Oxyz theo một trong ba cách cơ bản: qua một điểm và biết vectơ pháp tuyến; qua một điểm và biết cặp vectơ chỉ phương (suy ra vectơ pháp tuyến nhờ vào việc tìm vectơ vuông góc với cặp vectơ chỉ phương); qua ba điểm không thẳng hàng.' },
  { id: 'T12.26', strand: 'Hình học và Đo lường', topic: 'Phương trình mặt phẳng', sgk: 'Bài 14', text: 'Thiết lập được điều kiện để hai mặt phẳng song song, vuông góc với nhau.' },
  { id: 'T12.27', strand: 'Hình học và Đo lường', topic: 'Phương trình mặt phẳng', sgk: 'Bài 14', text: 'Tính được khoảng cách từ một điểm đến một mặt phẳng bằng phương pháp toạ độ.' },
  { id: 'T12.28', strand: 'Hình học và Đo lường', topic: 'Phương trình mặt phẳng', sgk: 'Bài 14', text: 'Vận dụng được kiến thức về phương trình mặt phẳng để giải một số bài toán liên quan đến thực tiễn.' },
  { id: 'T12.29', strand: 'Hình học và Đo lường', topic: 'Phương trình đường thẳng trong không gian', sgk: 'Bài 15', text: 'Nhận biết được phương trình chính tắc, phương trình tham số, vectơ chỉ phương của đường thẳng trong không gian.' },
  { id: 'T12.30', strand: 'Hình học và Đo lường', topic: 'Phương trình đường thẳng trong không gian', sgk: 'Bài 15', text: 'Thiết lập được phương trình của đường thẳng trong hệ trục toạ độ theo một trong hai cách cơ bản: qua một điểm và biết một vectơ chỉ phương, qua hai điểm.' },
  { id: 'T12.31', strand: 'Hình học và Đo lường', topic: 'Phương trình đường thẳng trong không gian', sgk: 'Bài 15', text: 'Xác định được điều kiện để hai đường thẳng chéo nhau, cắt nhau, song song hoặc vuông góc với nhau.' },
  { id: 'T12.32', strand: 'Hình học và Đo lường', topic: 'Phương trình đường thẳng trong không gian', sgk: 'Bài 16', text: 'Thiết lập được công thức tính góc giữa hai đường thẳng, giữa đường thẳng và mặt phẳng, giữa hai mặt phẳng.' },
  { id: 'T12.33', strand: 'Hình học và Đo lường', topic: 'Phương trình đường thẳng trong không gian', sgk: 'Bài 15', text: 'Vận dụng được kiến thức về phương trình đường thẳng trong không gian để giải một số bài toán liên quan đến thực tiễn.' },
  { id: 'T12.34', strand: 'Hình học và Đo lường', topic: 'Phương trình mặt cầu', sgk: 'Bài 17', text: 'Nhận biết được phương trình mặt cầu.' },
  { id: 'T12.35', strand: 'Hình học và Đo lường', topic: 'Phương trình mặt cầu', sgk: 'Bài 17', text: 'Xác định được tâm, bán kính của mặt cầu khi biết phương trình của nó.' },
  { id: 'T12.36', strand: 'Hình học và Đo lường', topic: 'Phương trình mặt cầu', sgk: 'Bài 17', text: 'Thiết lập được phương trình của mặt cầu khi biết tâm và bán kính.' },
  { id: 'T12.37', strand: 'Hình học và Đo lường', topic: 'Phương trình mặt cầu', sgk: 'Bài 17', text: 'Vận dụng được kiến thức về phương trình mặt cầu để giải một số bài toán liên quan đến thực tiễn.' },
  { id: 'T12.38', strand: 'Thống kê và Xác suất', topic: 'Số đặc trưng đo mức độ phân tán của mẫu số liệu ghép nhóm', sgk: 'Bài 9–10', text: 'Tính được các số đặc trưng đo mức độ phân tán cho mẫu số liệu ghép nhóm: khoảng biến thiên, khoảng tứ phân vị, phương sai, độ lệch chuẩn.' },
  { id: 'T12.39', strand: 'Thống kê và Xác suất', topic: 'Số đặc trưng đo mức độ phân tán của mẫu số liệu ghép nhóm', sgk: 'Bài 9–10', text: 'Giải thích được ý nghĩa và vai trò của các số đặc trưng nói trên của mẫu số liệu trong thực tiễn.' },
  { id: 'T12.40', strand: 'Thống kê và Xác suất', topic: 'Số đặc trưng đo mức độ phân tán của mẫu số liệu ghép nhóm', sgk: 'Bài 9–10', text: 'Chỉ ra được những kết luận nhờ ý nghĩa của các số đặc trưng nói trên của mẫu số liệu trong trường hợp đơn giản.' },
  { id: 'T12.41', strand: 'Thống kê và Xác suất', topic: 'Số đặc trưng đo mức độ phân tán của mẫu số liệu ghép nhóm', sgk: 'Bài 9–10', text: 'Nhận biết được mối liên hệ giữa thống kê với những kiến thức của các môn học khác trong Chương trình lớp 12 và trong thực tiễn.' },
  { id: 'T12.42', strand: 'Thống kê và Xác suất', topic: 'Xác suất có điều kiện', sgk: 'Bài 18', text: 'Nhận biết được khái niệm về xác suất có điều kiện.' },
  { id: 'T12.43', strand: 'Thống kê và Xác suất', topic: 'Xác suất có điều kiện', sgk: 'Bài 18', text: 'Giải thích được ý nghĩa của xác suất có điều kiện trong những tình huống thực tiễn quen thuộc.' },
  { id: 'T12.44', strand: 'Thống kê và Xác suất', topic: 'Công thức xác suất toàn phần và công thức Bayes', sgk: 'Bài 19', text: 'Mô tả được công thức xác suất toàn phần, công thức Bayes thông qua bảng dữ liệu thống kê 2x2 và sơ đồ hình cây.' },
  { id: 'T12.45', strand: 'Thống kê và Xác suất', topic: 'Công thức xác suất toàn phần và công thức Bayes', sgk: 'Bài 19', text: 'Sử dụng được công thức Bayes để tính xác suất có điều kiện và vận dụng vào một số bài toán thực tiễn.' },
  { id: 'T12.46', strand: 'Thống kê và Xác suất', topic: 'Công thức xác suất toàn phần và công thức Bayes', sgk: 'Bài 19', text: 'Sử dụng được sơ đồ hình cây để tính xác suất có điều kiện trong một số bài toán thực tiễn liên quan tới thống kê.' },
];

const BY_GRADE: Readonly<Record<number, readonly YccdItem[]>> = { 10: G10, 11: G11, 12: G12 };
const BY_ID = new Map<string, YccdItem>(Object.values(BY_GRADE).flatMap(list => list.map(item => [item.id, item] as const)));

/** Danh sách YCCĐ của khối (theo thứ tự Chương trình); khối chưa có dữ liệu → mảng rỗng. */
export const yccdForGrade = (grade: unknown): readonly YccdItem[] => {
  const n = Number(String(grade ?? '').match(/\d+/)?.[0]);
  return BY_GRADE[n] ?? [];
};

export const yccdById = (id: string): YccdItem | undefined => BY_ID.get(id);
