import { AdaptiveLesson } from './types';

export const sampleAdaptiveLesson: AdaptiveLesson = {
  id: 'adaptive-sample-math-lesson',
  title: 'Khung mẫu bài học phân hoá Toán THPT',
  subjectId: 'math',
  grade: '10',
  durationMinutes: 40,
  status: 'draft',
  teacherId: 'demo-teacher',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  curriculumRef: {
    programType: 'CUSTOM',
    week: 'Mẫu',
    period: 1,
    textbook: 'SGK Toán THPT',
    chapter: 'Chủ đề mẫu',
    lessonCode: 'MATH-ADAPTIVE-SAMPLE',
  },
  preparation: {
    textbookPages: 'Giáo viên cập nhật theo SGK đang sử dụng',
    readingInstructions: 'Học sinh đọc trước phần khái niệm, quan sát ví dụ mẫu trong SGK và ghi lại điểm chưa hiểu.',
    guidingQuestions: [
      'Khái niệm chính của bài học là gì?',
      'Điều kiện áp dụng kiến thức này nằm ở đâu?',
      'Dạng sai lầm nào em dễ mắc khi làm bài tương tự?',
    ],
    estimatedMinutes: 10,
  },
  fiveStepFlow: {
    steps: [
      {
        id: 'step-connect',
        name: 'Kết nối',
        purpose: 'Kích hoạt kiến thức nền và kiểm tra việc đọc trước.',
        estimatedMinutes: 3,
        teacherRole: 'Nêu vấn đề ngắn, nhắc lại mục tiêu tiết học.',
        studentAction: 'Trả lời câu hỏi gợi mở và chuẩn bị làm test đầu giờ.',
        systemSupport: 'Hiển thị câu hỏi định hướng và trạng thái chuẩn bị.',
      },
      {
        id: 'step-diagnose',
        name: 'Chẩn đoán',
        purpose: 'Xác định mức hiểu theo từng mục tiêu học tập.',
        estimatedMinutes: 7,
        teacherRole: 'Theo dõi tiến độ làm test.',
        studentAction: 'Làm bài test đầu giờ 5–7 phút.',
        systemSupport: 'Chấm nhanh, tính mastery và đề xuất tuyến học.',
      },
      {
        id: 'step-learn',
        name: 'Hình thành kiến thức',
        purpose: 'Cung cấp nội dung phù hợp với từng tuyến học.',
        estimatedMinutes: 15,
        teacherRole: 'Hỗ trợ học sinh bị kẹt hoặc sai cùng một lỗi.',
        studentAction: 'Học nội dung, xem ví dụ, trả lời câu hỏi ngắn.',
        systemSupport: 'Hiển thị nội dung foundation / standard / challenge.',
      },
      {
        id: 'step-practice',
        name: 'Luyện tập và điều chỉnh',
        purpose: 'Kiểm tra hiểu bài sau từng mảnh kiến thức.',
        estimatedMinutes: 10,
        teacherRole: 'Can thiệp nhóm cần hỗ trợ.',
        studentAction: 'Làm quick check và nhận giảng lại nếu cần.',
        systemSupport: 'Quyết định chuyển tiếp, giảng lại hoặc báo giáo viên.',
      },
      {
        id: 'step-reflect',
        name: 'Phản tư',
        purpose: 'Tổng kết tiến bộ và giao nhiệm vụ sau tiết.',
        estimatedMinutes: 5,
        teacherRole: 'Chốt kiến thức trọng tâm và định hướng bài sau.',
        studentAction: 'Làm exit ticket và đọc khuyến nghị cá nhân.',
        systemSupport: 'Tạo báo cáo cá nhân và dashboard lớp.',
      },
    ],
  },
  objectives: [
    {
      id: 'obj-concept',
      code: 'O1',
      title: 'Nhận diện khái niệm chính',
      description: 'Học sinh nêu được khái niệm, ký hiệu và điều kiện xuất hiện trong bài học.',
      bloomLevel: 'remember',
      masteryThreshold: 0.7,
      prerequisiteObjectiveIds: [],
      commonMisconceptions: [
        {
          id: 'mis-read-concept',
          title: 'Nhầm khái niệm với ví dụ',
          description: 'Học sinh nhớ ví dụ cụ thể nhưng chưa diễn đạt được bản chất khái niệm.',
          remediationHint: 'Yêu cầu học sinh so sánh hai ví dụ và chỉ ra điểm chung.',
        },
      ],
    },
    {
      id: 'obj-condition',
      code: 'O2',
      title: 'Xác định điều kiện áp dụng',
      description: 'Học sinh biết khi nào được dùng công thức hoặc phương pháp trong bài.',
      bloomLevel: 'understand',
      masteryThreshold: 0.7,
      prerequisiteObjectiveIds: ['obj-concept'],
      commonMisconceptions: [
        {
          id: 'mis-ignore-condition',
          title: 'Bỏ qua điều kiện',
          description: 'Học sinh áp dụng máy móc mà không kiểm tra điều kiện của bài toán.',
          remediationHint: 'Nhắc học sinh viết dòng kiểm tra điều kiện trước khi biến đổi.',
        },
      ],
    },
    {
      id: 'obj-procedure',
      code: 'O3',
      title: 'Thực hiện quy trình giải cơ bản',
      description: 'Học sinh làm được bài toán chuẩn theo các bước đã học.',
      bloomLevel: 'apply',
      masteryThreshold: 0.75,
      prerequisiteObjectiveIds: ['obj-concept', 'obj-condition'],
      commonMisconceptions: [
        {
          id: 'mis-step-order',
          title: 'Sai thứ tự bước giải',
          description: 'Học sinh biết công thức nhưng đặt sai trình tự xử lý.',
          remediationHint: 'Cho học sinh hoàn thiện sơ đồ bước giải còn thiếu.',
        },
      ],
    },
    {
      id: 'obj-transfer',
      code: 'O4',
      title: 'Vận dụng trong tình huống biến đổi',
      description: 'Học sinh xử lý được bài toán có thay đổi dữ kiện hoặc yêu cầu giải thích.',
      bloomLevel: 'analyze',
      masteryThreshold: 0.8,
      prerequisiteObjectiveIds: ['obj-procedure'],
      commonMisconceptions: [
        {
          id: 'mis-pattern-match',
          title: 'Nhận dạng máy móc',
          description: 'Học sinh chỉ làm được bài giống hệt ví dụ mẫu, gặp biến đổi thì lúng túng.',
          remediationHint: 'Yêu cầu học sinh nêu dấu hiệu nhận dạng thay vì nhìn hình thức bài.',
        },
      ],
    },
  ],
  diagnosticTest: {
    id: 'diagnostic-sample',
    title: 'Test đầu giờ mẫu',
    purpose: 'diagnostic',
    durationMinutes: 7,
    questions: [
      {
        id: 'dq1',
        type: 'multiple_choice',
        prompt: 'Câu nào mô tả đúng nhất vai trò của khái niệm chính trong bài học?',
        options: ['Một ví dụ cụ thể', 'Một quy tắc dùng để nhận diện và xử lý bài toán', 'Một phép tính phụ', 'Một ký hiệu không ảnh hưởng lời giải'],
        correctAnswer: 'Một quy tắc dùng để nhận diện và xử lý bài toán',
        explanation: 'Khái niệm chính không chỉ là ví dụ; nó giúp nhận diện bản chất và chọn phương pháp giải.',
        objectiveIds: ['obj-concept'],
        misconceptionIds: ['mis-read-concept'],
        difficulty: 'easy',
        points: 1,
      },
      {
        id: 'dq2',
        type: 'multiple_choice',
        prompt: 'Trước khi áp dụng một công thức hoặc phương pháp, bước nào cần được kiểm tra?',
        options: ['Điều kiện áp dụng', 'Độ dài lời giải', 'Số dòng trình bày', 'Tên chương học'],
        correctAnswer: 'Điều kiện áp dụng',
        explanation: 'Bỏ qua điều kiện là nguyên nhân phổ biến dẫn đến lời giải sai dù biến đổi đúng.',
        objectiveIds: ['obj-condition'],
        misconceptionIds: ['mis-ignore-condition'],
        difficulty: 'easy',
        points: 1,
      },
      {
        id: 'dq3',
        type: 'short_answer',
        prompt: 'Viết ngắn gọn tên bước đầu tiên em nên làm khi gặp một bài toán dạng chuẩn.',
        correctAnswer: 'xác định dữ kiện',
        explanation: 'Với bài chuẩn, cần xác định dữ kiện và yêu cầu trước khi chọn công thức.',
        objectiveIds: ['obj-procedure'],
        misconceptionIds: ['mis-step-order'],
        difficulty: 'medium',
        points: 1,
      },
      {
        id: 'dq4',
        type: 'multiple_choice',
        prompt: 'Nếu bài toán thay đổi cách hỏi so với ví dụ mẫu, em nên làm gì trước?',
        options: ['Tìm dấu hiệu bản chất của dạng toán', 'Bỏ qua bài đó', 'Áp dụng y hệt ví dụ', 'Chỉ nhìn đáp án'],
        correctAnswer: 'Tìm dấu hiệu bản chất của dạng toán',
        explanation: 'Bài vận dụng yêu cầu nhận ra bản chất, không chỉ khớp mẫu hình thức.',
        objectiveIds: ['obj-transfer'],
        misconceptionIds: ['mis-pattern-match'],
        difficulty: 'hard',
        points: 1,
      },
    ],
  },
  knowledgeUnits: [
    {
      id: 'unit-concept',
      title: 'Mảnh 1: Hiểu khái niệm và điều kiện',
      objectiveIds: ['obj-concept', 'obj-condition'],
      estimatedMinutes: 10,
      maxRemediationAttempts: 2,
      routes: [
        {
          route: 'foundation',
          explanation: 'Tuyến củng cố bắt đầu bằng việc tách khái niệm khỏi ví dụ. Em hãy đọc một ví dụ, sau đó chỉ ra điểm chung lặp lại trong các bài tương tự.',
          workedExamples: [
            {
              id: 'ex-foundation-1',
              title: 'Ví dụ nhận diện bản chất',
              problem: 'Cho một tình huống mẫu. Hãy gạch chân dữ kiện và khoanh tròn yêu cầu.',
              solution: 'Dữ kiện là phần đã cho; yêu cầu là điều cần tìm hoặc chứng minh.',
              explanation: 'Khi phân biệt rõ dữ kiện và yêu cầu, em sẽ tránh áp dụng công thức máy móc.',
              objectiveIds: ['obj-concept', 'obj-condition'],
            },
          ],
          practiceTasks: [
            {
              id: 'pt-foundation-1',
              prompt: 'Hãy viết một câu mô tả điều kiện cần kiểm tra trước khi giải.',
              expectedAnswer: 'Cần kiểm tra điều kiện áp dụng của công thức hoặc phương pháp.',
              hints: ['Điều kiện thường nằm ở giả thiết hoặc định nghĩa.', 'Hãy tự hỏi: khi nào công thức này được dùng?'],
              objectiveIds: ['obj-condition'],
              difficulty: 'easy',
            },
          ],
        },
        {
          route: 'standard',
          explanation: 'Tuyến chuẩn tập trung vào việc nối khái niệm với điều kiện áp dụng và ví dụ mẫu. Em cần nêu được khái niệm, điều kiện, rồi mới thực hiện bước giải.',
          workedExamples: [
            {
              id: 'ex-standard-1',
              title: 'Ví dụ chuẩn',
              problem: 'Nhận diện dạng toán, kiểm tra điều kiện, sau đó chọn phương pháp giải.',
              solution: 'Bước 1: đọc dữ kiện. Bước 2: kiểm tra điều kiện. Bước 3: chọn công thức hoặc phương pháp.',
              explanation: 'Quy trình ba bước giúp lời giải có căn cứ và ít sai sót.',
              objectiveIds: ['obj-concept', 'obj-condition'],
            },
          ],
          practiceTasks: [
            {
              id: 'pt-standard-1',
              prompt: 'Sắp xếp ba bước: chọn phương pháp, đọc dữ kiện, kiểm tra điều kiện.',
              expectedAnswer: 'Đọc dữ kiện → kiểm tra điều kiện → chọn phương pháp.',
              hints: ['Không chọn phương pháp trước khi biết điều kiện.', 'Dữ kiện luôn cần đọc đầu tiên.'],
              objectiveIds: ['obj-procedure'],
              difficulty: 'medium',
            },
          ],
        },
        {
          route: 'challenge',
          explanation: 'Tuyến thử thách yêu cầu em giải thích vì sao điều kiện áp dụng là cần thiết. Hãy tìm một phản ví dụ nếu bỏ qua điều kiện.',
          workedExamples: [
            {
              id: 'ex-challenge-1',
              title: 'Phản ví dụ về điều kiện',
              problem: 'Nêu một tình huống trong đó áp dụng công thức mà không kiểm tra điều kiện sẽ dẫn đến kết luận sai.',
              solution: 'Nếu điều kiện nền không thoả mãn, công thức không còn đảm bảo đúng, nên kết luận có thể sai.',
              explanation: 'Tư duy phản ví dụ giúp em hiểu sâu hơn bản chất kiến thức.',
              objectiveIds: ['obj-condition', 'obj-transfer'],
            },
          ],
          practiceTasks: [
            {
              id: 'pt-challenge-1',
              prompt: 'Viết một câu giải thích vì sao phải kiểm tra điều kiện trước khi biến đổi.',
              expectedAnswer: 'Vì công thức hoặc phương pháp chỉ đúng trong phạm vi điều kiện nhất định.',
              hints: ['Hãy dùng cụm “chỉ đúng khi...”.'],
              objectiveIds: ['obj-transfer'],
              difficulty: 'hard',
            },
          ],
        },
      ],
      quickCheck: {
        id: 'qc-unit-concept',
        title: 'Kiểm tra nhanh mảnh 1',
        purpose: 'quick_check',
        durationMinutes: 3,
        questions: [
          {
            id: 'qc1',
            type: 'multiple_choice',
            prompt: 'Điểm cần kiểm tra trước khi áp dụng phương pháp là gì?',
            options: ['Điều kiện áp dụng', 'Số trang SGK', 'Tên người giải', 'Thời gian còn lại'],
            correctAnswer: 'Điều kiện áp dụng',
            explanation: 'Điều kiện áp dụng quyết định phương pháp có hợp lệ hay không.',
            objectiveIds: ['obj-condition'],
            misconceptionIds: ['mis-ignore-condition'],
            difficulty: 'easy',
            points: 1,
          },
          {
            id: 'qc2',
            type: 'short_answer',
            prompt: 'Viết cụm từ còn thiếu: Đọc dữ kiện → kiểm tra điều kiện → ...',
            correctAnswer: 'chọn phương pháp',
            explanation: 'Sau khi đã rõ dữ kiện và điều kiện, học sinh mới chọn phương pháp giải.',
            objectiveIds: ['obj-procedure'],
            misconceptionIds: ['mis-step-order'],
            difficulty: 'medium',
            points: 1,
          },
        ],
      },
    },
  ],
  exitTicket: {
    id: 'exit-sample',
    title: 'Exit ticket mẫu',
    purpose: 'exit_ticket',
    durationMinutes: 4,
    questions: [
      {
        id: 'exit1',
        type: 'short_answer',
        prompt: 'Hôm nay em cần nhớ nhất bước nào để tránh sai khi làm bài?',
        correctAnswer: 'kiểm tra điều kiện',
        explanation: 'Kiểm tra điều kiện giúp tránh áp dụng máy móc.',
        objectiveIds: ['obj-condition'],
        difficulty: 'easy',
        points: 1,
      },
      {
        id: 'exit2',
        type: 'multiple_choice',
        prompt: 'Khi gặp bài biến đổi khác ví dụ mẫu, hướng xử lý phù hợp là gì?',
        options: ['Tìm dấu hiệu bản chất', 'Chép lại ví dụ', 'Bỏ qua điều kiện', 'Đoán nhanh đáp án'],
        correctAnswer: 'Tìm dấu hiệu bản chất',
        explanation: 'Tình huống biến đổi cần nhận diện bản chất trước khi chọn cách giải.',
        objectiveIds: ['obj-transfer'],
        difficulty: 'hard',
        points: 1,
      },
    ],
  },
};
