import { AdaptiveLesson } from './types';

export const sampleAdaptiveLesson: AdaptiveLesson = {
  id: 'adaptive-math-11-arithmetic-sequence',
  title: 'Toán 11 — Cấp số cộng',
  subjectId: 'math',
  grade: '11',
  durationMinutes: 40,
  pacingPolicy: {
    minExitTicketMinutes: 5,
    aheadThresholdMinutes: 5,
    behindThresholdMinutes: 4,
    stuckAfterRemediationAttempts: 2,
    enrichmentTriggerMastery: 0.85,
    supportTriggerMastery: 0.55,
  },
  status: 'draft',
  teacherId: 'demo-teacher',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  curriculumRef: {
    programType: 'CUSTOM',
    week: 'Dạy thử',
    period: 1,
    textbook: 'SGK Toán 11',
    chapter: 'Dãy số, cấp số cộng và cấp số nhân',
    lessonCode: 'MATH11-CAP-SO-CONG',
  },
  preparation: {
    textbookPages: 'Phần Cấp số cộng trong SGK Toán 11 đang sử dụng tại lớp',
    readingInstructions: 'Học sinh đọc trước định nghĩa cấp số cộng, công thức số hạng tổng quát và công thức tổng n số hạng đầu. Ghi lại ít nhất một điểm chưa hiểu.',
    guidingQuestions: [
      'Một dãy số cần thỏa điều kiện gì để là cấp số cộng?',
      'Công sai d của cấp số cộng được xác định như thế nào?',
      'Nếu biết u1 và d, làm thế nào để tính u_n?',
      'Khi nào cần dùng công thức tổng S_n?',
    ],
    estimatedMinutes: 12,
  },
  fiveStepFlow: {
    steps: [
      {
        id: 'step-connect',
        name: 'Kết nối',
        purpose: 'Gợi lại kiến thức về dãy số và quan sát quy luật tăng/giảm đều.',
        estimatedMinutes: 3,
        teacherRole: 'Đưa ví dụ dãy số quen thuộc như 2, 5, 8, 11,... và hỏi học sinh nhận xét quy luật.',
        studentAction: 'Nhận diện sự thay đổi giữa hai số hạng liên tiếp.',
        systemSupport: 'Hiển thị câu hỏi gợi mở và nhắc lại phần đã đọc trước ở nhà.',
      },
      {
        id: 'step-diagnose',
        name: 'Chẩn đoán',
        purpose: 'Kiểm tra nhanh mức nắm định nghĩa, công sai, số hạng tổng quát và tổng n số hạng đầu.',
        estimatedMinutes: 7,
        teacherRole: 'Theo dõi số học sinh hoàn thành test đầu giờ và nhóm cần hỗ trợ.',
        studentAction: 'Làm bài test đầu giờ gồm 5 câu trong 5–7 phút.',
        systemSupport: 'Chấm theo từng mục tiêu và phân tuyến Củng cố / Chuẩn / Thử thách.',
      },
      {
        id: 'step-learn',
        name: 'Hình thành kiến thức',
        purpose: 'Học định nghĩa, công thức u_n và công thức S_n theo tuyến phù hợp.',
        estimatedMinutes: 15,
        teacherRole: 'Hỗ trợ trực tiếp nhóm còn nhầm định nghĩa hoặc công sai.',
        studentAction: 'Đọc nội dung theo tuyến, tự viết ý tưởng cho ví dụ có tính giờ, nhận gợi ý khi cần rồi mới xem lời giải sau khi nộp.',
        systemSupport: 'Hiển thị lời giải thích, ví dụ tương tác, timer, gợi ý theo thời gian và nhiệm vụ luyện tập theo tuyến học.',
      },
      {
        id: 'step-practice',
        name: 'Luyện tập và điều chỉnh',
        purpose: 'Kiểm tra sau mảnh kiến thức, giảng lại nếu học sinh chưa đạt.',
        estimatedMinutes: 10,
        teacherRole: 'Can thiệp với học sinh sai hai lần liên tiếp hoặc bỏ qua điều kiện.',
        studentAction: 'Làm quick check, nhận phản hồi và học lại nếu cần.',
        systemSupport: 'Quyết định chuyển bước, giảng lại hoặc đánh dấu cần giáo viên hỗ trợ.',
      },
      {
        id: 'step-reflect',
        name: 'Phản tư',
        purpose: 'Tổng kết cách nhận diện và vận dụng cấp số cộng.',
        estimatedMinutes: 5,
        teacherRole: 'Chốt ba câu hỏi: có phải cấp số cộng không, tìm u_n thế nào, dùng S_n khi nào.',
        studentAction: 'Làm exit ticket và đọc khuyến nghị cá nhân.',
        systemSupport: 'Tạo báo cáo ngắn cho học sinh và dashboard mục tiêu cho giáo viên.',
      },
    ],
  },
  objectives: [
    {
      id: 'obj-identify-ap',
      code: 'O1',
      title: 'Nhận diện cấp số cộng',
      description: 'Học sinh xác định được một dãy số có phải cấp số cộng hay không thông qua hiệu hai số hạng liên tiếp.',
      bloomLevel: 'understand',
      masteryThreshold: 0.7,
      prerequisiteObjectiveIds: [],
      commonMisconceptions: [
        {
          id: 'mis-constant-pattern',
          title: 'Nhầm quy luật bất kỳ với cấp số cộng',
          description: 'Học sinh thấy dãy có quy luật nhưng không kiểm tra hiệu hai số hạng liên tiếp có không đổi hay không.',
          remediationHint: 'Yêu cầu học sinh lập bảng u_{n+1} - u_n cho ít nhất ba cặp liên tiếp.',
        },
      ],
    },
    {
      id: 'obj-common-difference',
      code: 'O2',
      title: 'Xác định công sai',
      description: 'Học sinh tính đúng công sai d = u_{n+1} - u_n và hiểu công sai có thể âm, dương hoặc bằng 0.',
      bloomLevel: 'apply',
      masteryThreshold: 0.75,
      prerequisiteObjectiveIds: ['obj-identify-ap'],
      commonMisconceptions: [
        {
          id: 'mis-wrong-d-order',
          title: 'Tính ngược công sai',
          description: 'Học sinh lấy u_n - u_{n+1} thay vì u_{n+1} - u_n nên sai dấu của d.',
          remediationHint: 'Nhấn mạnh chiều đi từ số hạng trước sang số hạng sau: sau trừ trước.',
        },
      ],
    },
    {
      id: 'obj-general-term',
      code: 'O3',
      title: 'Tính số hạng tổng quát',
      description: 'Học sinh vận dụng công thức u_n = u_1 + (n - 1)d để tìm số hạng bất kỳ hoặc tìm n khi biết u_n.',
      bloomLevel: 'apply',
      masteryThreshold: 0.75,
      prerequisiteObjectiveIds: ['obj-common-difference'],
      commonMisconceptions: [
        {
          id: 'mis-use-n-not-n-minus-1',
          title: 'Dùng n.d thay vì (n - 1)d',
          description: 'Học sinh quên rằng từ u_1 đến u_n chỉ có n - 1 khoảng công sai.',
          remediationHint: 'Cho học sinh đếm số bước nhảy từ u_1 đến u_2, u_3, u_4 để thấy hệ số là n - 1.',
        },
      ],
    },
    {
      id: 'obj-sum-first-n',
      code: 'O4',
      title: 'Tính tổng n số hạng đầu',
      description: 'Học sinh sử dụng đúng công thức S_n = n(u_1 + u_n)/2 hoặc S_n = n[2u_1 + (n - 1)d]/2.',
      bloomLevel: 'apply',
      masteryThreshold: 0.75,
      prerequisiteObjectiveIds: ['obj-general-term'],
      commonMisconceptions: [
        {
          id: 'mis-sum-vs-term',
          title: 'Nhầm số hạng u_n với tổng S_n',
          description: 'Học sinh tính u_n nhưng trả lời như đó là tổng hoặc ngược lại.',
          remediationHint: 'Yêu cầu học sinh gạch chân từ khóa “số hạng thứ n” và “tổng n số hạng đầu”.',
        },
      ],
    },
    {
      id: 'obj-context-ap',
      code: 'O5',
      title: 'Vận dụng vào tình huống thực tế',
      description: 'Học sinh mô hình hóa được tình huống tăng/giảm đều bằng cấp số cộng và giải thích kết quả.',
      bloomLevel: 'analyze',
      masteryThreshold: 0.8,
      prerequisiteObjectiveIds: ['obj-general-term', 'obj-sum-first-n'],
      commonMisconceptions: [
        {
          id: 'mis-context-index',
          title: 'Sai mốc chỉ số trong bài toán thực tế',
          description: 'Học sinh nhầm tháng/ngày/lần đầu là n = 0 hay n = 1, dẫn đến lệch một công sai.',
          remediationHint: 'Yêu cầu học sinh xác định rõ đại lượng nào là u_1 trước khi viết công thức.',
        },
      ],
    },
  ],
  diagnosticTest: {
    id: 'diagnostic-ap',
    title: 'Test đầu giờ — Cấp số cộng',
    purpose: 'diagnostic',
    durationMinutes: 7,
    questions: [
      {
        id: 'dq1',
        type: 'multiple_choice',
        prompt: 'Dãy nào sau đây là cấp số cộng?',
        options: ['2, 4, 8, 16', '1, 4, 7, 10', '1, 2, 4, 7', '3, 6, 12, 24'],
        correctAnswer: '1, 4, 7, 10',
        explanation: 'Dãy 1, 4, 7, 10 có hiệu hai số hạng liên tiếp đều bằng 3 nên là cấp số cộng.',
        objectiveIds: ['obj-identify-ap'],
        misconceptionIds: ['mis-constant-pattern'],
        difficulty: 'easy',
        points: 1,
      },
      {
        id: 'dq2',
        type: 'multiple_choice',
        prompt: 'Cấp số cộng có u_1 = 7, u_2 = 3. Công sai d bằng bao nhiêu?',
        options: ['4', '-4', '10', '-10'],
        correctAnswer: '-4',
        explanation: 'Công sai d = u_2 - u_1 = 3 - 7 = -4.',
        objectiveIds: ['obj-common-difference'],
        misconceptionIds: ['mis-wrong-d-order'],
        difficulty: 'easy',
        points: 1,
      },
      {
        id: 'dq3',
        type: 'multiple_choice',
        prompt: 'Cấp số cộng có u_1 = 2 và d = 5. Số hạng u_6 bằng bao nhiêu?',
        options: ['27', '32', '25', '30'],
        correctAnswer: '27',
        explanation: 'u_6 = u_1 + (6 - 1)d = 2 + 5 · 5 = 27.',
        objectiveIds: ['obj-general-term'],
        misconceptionIds: ['mis-use-n-not-n-minus-1'],
        difficulty: 'medium',
        points: 1,
      },
      {
        id: 'dq4',
        type: 'multiple_choice',
        prompt: 'Cấp số cộng có u_1 = 1, u_5 = 9. Tổng 5 số hạng đầu S_5 bằng bao nhiêu?',
        options: ['25', '45', '10', '20'],
        correctAnswer: '25',
        explanation: 'S_5 = 5(u_1 + u_5)/2 = 5(1 + 9)/2 = 25.',
        objectiveIds: ['obj-sum-first-n'],
        misconceptionIds: ['mis-sum-vs-term'],
        difficulty: 'medium',
        points: 1,
      },
      {
        id: 'dq5',
        type: 'multiple_choice',
        prompt: 'Một bạn tiết kiệm tuần đầu 20 nghìn đồng, mỗi tuần sau tăng thêm 5 nghìn đồng. Số tiền tiết kiệm ở tuần thứ 6 là bao nhiêu?',
        options: ['45 nghìn đồng', '50 nghìn đồng', '30 nghìn đồng', '120 nghìn đồng'],
        correctAnswer: '45 nghìn đồng',
        explanation: 'Tuần đầu là u_1 = 20, d = 5. Tuần thứ 6: u_6 = 20 + (6 - 1) · 5 = 45 nghìn đồng.',
        objectiveIds: ['obj-context-ap', 'obj-general-term'],
        misconceptionIds: ['mis-context-index', 'mis-use-n-not-n-minus-1'],
        difficulty: 'hard',
        points: 1,
      },
    ],
  },
  knowledgeUnits: [
    {
      id: 'unit-identify-and-d',
      title: 'Mảnh 1: Nhận diện cấp số cộng và công sai',
      objectiveIds: ['obj-identify-ap', 'obj-common-difference'],
      estimatedMinutes: 10,
      maxRemediationAttempts: 2,
      coreTaskIds: ['pt-foundation-1', 'pt-standard-1'],
      supportTasks: [
        {
          id: 'support-identify-d-table',
          prompt: 'Điền bảng hiệu liên tiếp cho dãy 8, 5, 2, -1: 5 - 8 = ?, 2 - 5 = ?, -1 - 2 = ?. Kết luận dãy có phải cấp số cộng không.',
          expectedAnswer: 'Các hiệu đều bằng -3 nên là cấp số cộng, d = -3.',
          hints: ['Luôn lấy số sau trừ số trước.', 'Nếu ba hiệu bằng nhau thì dãy là cấp số cộng.'],
          objectiveIds: ['obj-identify-ap', 'obj-common-difference'],
          difficulty: 'easy',
        },
      ],
      enrichmentTasks: [
        {
          id: 'enrich-identify-create-counterexample',
          prompt: 'Tạo hai dãy số: một dãy là cấp số cộng có công sai âm, một dãy có quy luật rõ nhưng không phải cấp số cộng. Giải thích bằng hiệu liên tiếp.',
          expectedAnswer: 'Ví dụ: 10, 7, 4, 1 là cấp số cộng d = -3; 1, 2, 4, 8 không phải vì hiệu 1, 2, 4 không bằng nhau.',
          hints: ['Dãy không phải cấp số cộng có thể là dãy nhân đôi.', 'Lập bảng hiệu để chứng minh.'],
          objectiveIds: ['obj-identify-ap', 'obj-common-difference', 'obj-context-ap'],
          difficulty: 'hard',
        },
      ],
      externalToolIds: ['cscn', 'tinhcapso'],
      routes: [
        {
          route: 'foundation',
          explanation: 'Cấp số cộng là dãy số mà từ số hạng này sang số hạng kế tiếp, ta luôn cộng cùng một số không đổi. Số không đổi đó gọi là công sai d. Để kiểm tra, em hãy lấy số sau trừ số trước ở nhiều cặp liên tiếp. Nếu các hiệu bằng nhau, dãy là cấp số cộng.',
          workedExamples: [
            {
              id: 'ex-foundation-1',
              title: 'Kiểm tra từng hiệu liên tiếp',
              problem: 'Dãy 4, 7, 10, 13 có phải cấp số cộng không?',
              solution: 'Ta tính từng hiệu liên tiếp:\n\n7 - 4 = 3.\n\n10 - 7 = 3.\n\n13 - 10 = 3.\n\nCác hiệu đều bằng 3 nên dãy là cấp số cộng với công sai d = 3.',
              explanation: 'Điểm quan trọng là phải kiểm tra hiệu giữa hai số hạng liên tiếp, không chỉ nhìn thấy dãy tăng đều bằng cảm giác.',
              objectiveIds: ['obj-identify-ap', 'obj-common-difference'],
              timeLimitSeconds: 120,
              hintDelaySeconds: 60,
              hints: ['Hãy lấy số sau trừ số trước cho từng cặp liên tiếp.', 'Nếu các hiệu liên tiếp bằng nhau thì đó là cấp số cộng; giá trị chung chính là công sai d.'],
              responseMode: 'short_text',
            },
          ],
          practiceTasks: [
            {
              id: 'pt-foundation-1',
              prompt: 'Dãy 9, 6, 3, 0 có phải cấp số cộng không? Nếu có, công sai là bao nhiêu?',
              expectedAnswer: 'Có, d = -3.',
              hints: ['Lấy số sau trừ số trước.', '6 - 9 = -3, tiếp tục kiểm tra các cặp sau.'],
              objectiveIds: ['obj-identify-ap', 'obj-common-difference'],
              difficulty: 'easy',
            },
          ],
        },
        {
          route: 'standard',
          explanation: 'Với dãy (u_n), nếu u_{n+1} - u_n = d không đổi với mọi n thì dãy là cấp số cộng. Công sai d cho biết mỗi bước từ u_n sang u_{n+1} thay đổi bao nhiêu đơn vị.',
          workedExamples: [
            {
              id: 'ex-standard-1',
              title: 'Nhận diện bằng công thức hiệu',
              problem: 'Cho dãy 12, 8, 4, 0, -4. Hãy xác định dãy có phải cấp số cộng không và tìm d.',
              solution: 'Ta tính các hiệu theo đúng chiều số sau trừ số trước:\n\n8 - 12 = -4.\n\n4 - 8 = -4.\n\n0 - 4 = -4.\n\n-4 - 0 = -4.\n\nVậy dãy là cấp số cộng với công sai d = -4.',
              explanation: 'Công sai âm nghĩa là dãy giảm đều. Dấu âm không làm dãy mất tính chất cấp số cộng.',
              objectiveIds: ['obj-identify-ap', 'obj-common-difference'],
              timeLimitSeconds: 150,
              hintDelaySeconds: 75,
              hints: ['Đừng chỉ nhìn dãy đang giảm; hãy kiểm tra từng hiệu liên tiếp.', 'Công sai được tính bằng số hạng sau trừ số hạng trước, nên kết quả có thể âm.'],
              responseMode: 'long_text',
            },
          ],
          practiceTasks: [
            {
              id: 'pt-standard-1',
              prompt: 'Trong các dãy sau, dãy nào là cấp số cộng: A. 1, 3, 6, 10; B. 15, 11, 7, 3; C. 2, 4, 8, 16?',
              expectedAnswer: 'B là cấp số cộng với d = -4.',
              hints: ['Tính hiệu liên tiếp cho từng dãy.', 'Dãy cấp số cộng phải có hiệu không đổi.'],
              objectiveIds: ['obj-identify-ap'],
              difficulty: 'medium',
            },
          ],
        },
        {
          route: 'challenge',
          explanation: 'Ngoài việc kiểm tra hiệu liên tiếp, em cần giải thích được vì sao một quy luật nhìn có vẻ đều nhưng không phải cấp số cộng. Một dãy tăng theo quy luật nhân đôi hoặc tăng thêm lượng thay đổi không đều thì không phải cấp số cộng.',
          workedExamples: [
            {
              id: 'ex-challenge-1',
              title: 'Phân biệt quy luật cộng và quy luật khác',
              problem: 'Dãy 1, 2, 4, 7, 11 có phải cấp số cộng không? Giải thích.',
              solution: 'Ta có:\n\n2 - 1 = 1.\n\n4 - 2 = 2.\n\n7 - 4 = 3.\n\n11 - 7 = 4.\n\nCác hiệu lần lượt là 1, 2, 3, 4 nên không bằng nhau. Vì vậy dãy không phải cấp số cộng.',
              explanation: 'Dãy có quy luật tăng thêm 1, 2, 3, 4 nhưng công sai không cố định. Một dãy có quy luật chưa chắc là cấp số cộng.',
              objectiveIds: ['obj-identify-ap', 'obj-context-ap'],
              timeLimitSeconds: 180,
              hintDelaySeconds: 90,
              hints: ['Hãy viết ra tất cả hiệu liên tiếp thay vì kết luận từ cảm giác quy luật.', 'Nếu hiệu tăng dần 1, 2, 3, 4 thì công sai có cố định không?'],
              responseMode: 'long_text',
            },
          ],
          practiceTasks: [
            {
              id: 'pt-challenge-1',
              prompt: 'Tạo một dãy có quy luật rõ ràng nhưng không phải cấp số cộng, rồi giải thích vì sao.',
              expectedAnswer: 'Ví dụ: 2, 4, 8, 16 vì các hiệu 2, 4, 8 không bằng nhau.',
              hints: ['Có thể dùng dãy nhân đôi.', 'Hãy chứng minh bằng hiệu liên tiếp.'],
              objectiveIds: ['obj-identify-ap', 'obj-context-ap'],
              difficulty: 'hard',
            },
          ],
        },
      ],
      quickCheck: {
        id: 'qc-unit-identify-and-d',
        title: 'Kiểm tra nhanh mảnh 1',
        purpose: 'quick_check',
        durationMinutes: 3,
        questions: [
          {
            id: 'qc1',
            type: 'multiple_choice',
            prompt: 'Dãy 5, 2, -1, -4 là cấp số cộng với công sai nào?',
            options: ['3', '-3', '2', '-1'],
            correctAnswer: '-3',
            explanation: 'Công sai d = 2 - 5 = -3, các hiệu tiếp theo cũng bằng -3.',
            objectiveIds: ['obj-common-difference'],
            misconceptionIds: ['mis-wrong-d-order'],
            difficulty: 'easy',
            points: 1,
          },
          {
            id: 'qc2',
            type: 'multiple_choice',
            prompt: 'Dãy nào không phải cấp số cộng?',
            options: ['2, 5, 8, 11', '10, 7, 4, 1', '1, 2, 4, 8', '6, 6, 6, 6'],
            correctAnswer: '1, 2, 4, 8',
            explanation: 'Dãy 1, 2, 4, 8 có các hiệu 1, 2, 4 không bằng nhau.',
            objectiveIds: ['obj-identify-ap'],
            misconceptionIds: ['mis-constant-pattern'],
            difficulty: 'medium',
            points: 1,
          },
        ],
      },
    },
    {
      id: 'unit-general-term-and-sum',
      title: 'Mảnh 2: Số hạng tổng quát và tổng n số hạng đầu',
      objectiveIds: ['obj-general-term', 'obj-sum-first-n', 'obj-context-ap'],
      estimatedMinutes: 15,
      maxRemediationAttempts: 2,
      coreTaskIds: ['pt-foundation-2', 'pt-standard-2'],
      supportTasks: [
        {
          id: 'support-general-term-steps',
          prompt: 'Cho u_1 = 5, d = 2. Hoàn thành từng bước: từ u_1 đến u_4 có mấy bước nhảy? Tính u_4.',
          expectedAnswer: 'Có 3 bước nhảy, u_4 = 5 + 3 · 2 = 11.',
          hints: ['Từ u_1 đến u_4 không phải 4 bước mà là 3 bước.', 'Dùng u_n = u_1 + (n - 1)d.'],
          objectiveIds: ['obj-general-term'],
          difficulty: 'easy',
        },
        {
          id: 'support-sum-keyword',
          prompt: 'Gạch chân từ khóa trong câu: “Tính tổng 6 số hạng đầu”. Đại lượng cần tính là u_6 hay S_6?',
          expectedAnswer: 'Cần tính S_6.',
          hints: ['Từ “tổng” tương ứng với S_n.', 'u_n chỉ là một số hạng.'],
          objectiveIds: ['obj-sum-first-n'],
          difficulty: 'easy',
        },
      ],
      enrichmentTasks: [
        {
          id: 'enrich-ap-context-design',
          prompt: 'Thiết kế một bài toán thực tế dùng cấp số cộng có cả yêu cầu tìm u_n và S_n, rồi tự giải.',
          expectedAnswer: 'Ví dụ tiết kiệm/thể thao/xếp ghế; cần xác định u_1, d, n, sau đó tính đúng u_n và S_n.',
          hints: ['Chọn tình huống tăng hoặc giảm đều.', 'Đặt một câu hỏi về giá trị ở lần thứ n và một câu hỏi về tổng n lần.'],
          objectiveIds: ['obj-general-term', 'obj-sum-first-n', 'obj-context-ap'],
          difficulty: 'hard',
        },
      ],
      externalToolIds: ['bancovua', 'ranangoanCS', 'tranhdau'],
      routes: [
        {
          route: 'foundation',
          explanation: 'Từ u_1 đến u_n có n - 1 bước nhảy, nên u_n = u_1 + (n - 1)d. Khi cần cộng nhiều số hạng đầu, dùng S_n = n(u_1 + u_n)/2 nếu biết u_n, hoặc S_n = n[2u_1 + (n - 1)d]/2 nếu biết u_1 và d.',
          workedExamples: [
            {
              id: 'ex-foundation-2',
              title: 'Đếm số bước nhảy',
              problem: 'Cho u_1 = 3, d = 2. Tính u_5.',
              solution: 'Từ u_1 đến u_5 có 4 bước nhảy.\n\nÁp dụng công thức u_n = u_1 + (n - 1)d.\n\nu_5 = 3 + (5 - 1) · 2 = 3 + 8 = 11.',
              explanation: 'Không dùng 5 · 2 vì u_1 đã là số hạng đầu, chỉ cần thêm 4 lần công sai.',
              objectiveIds: ['obj-general-term'],
              timeLimitSeconds: 150,
              hintDelaySeconds: 75,
              hints: ['Từ u_1 đến u_5 có bao nhiêu khoảng nhảy?', 'Dùng công thức u_n = u_1 + (n - 1)d, chú ý phần n - 1.'],
              responseMode: 'short_text',
            },
          ],
          practiceTasks: [
            {
              id: 'pt-foundation-2',
              prompt: 'Cho u_1 = 4, d = 3. Tính u_6.',
              expectedAnswer: 'u_6 = 4 + 5 · 3 = 19.',
              hints: ['Từ u_1 đến u_6 có 5 bước.', 'Dùng u_n = u_1 + (n - 1)d.'],
              objectiveIds: ['obj-general-term'],
              difficulty: 'easy',
            },
          ],
        },
        {
          route: 'standard',
          explanation: 'Ở tuyến chuẩn, em cần chọn đúng công thức theo yêu cầu: nếu đề hỏi “số hạng thứ n” thì tính u_n; nếu đề hỏi “tổng n số hạng đầu” thì tính S_n. Hãy gạch chân từ khóa trước khi làm.',
          workedExamples: [
            {
              id: 'ex-standard-2',
              title: 'Phân biệt u_n và S_n',
              problem: 'Cho cấp số cộng có u_1 = 2, d = 3. Tính u_8 và S_8.',
              solution: 'Trước hết tính số hạng thứ 8:\n\nu_8 = 2 + (8 - 1) · 3 = 2 + 21 = 23.\n\nSau đó tính tổng 8 số hạng đầu:\n\nS_8 = 8(2 + 23)/2 = 4 · 25 = 100.',
              explanation: 'u_8 là một số hạng, còn S_8 là tổng của 8 số hạng đầu. Cần tách rõ hai yêu cầu để không nhầm kết quả.',
              objectiveIds: ['obj-general-term', 'obj-sum-first-n'],
              timeLimitSeconds: 210,
              hintDelaySeconds: 105,
              hints: ['Đề có hai yêu cầu: tính u_8 trước, rồi dùng u_8 để tính S_8.', 'Công thức tổng có thể dùng S_n = n(u_1 + u_n)/2 khi đã biết u_n.'],
              responseMode: 'long_text',
            },
          ],
          practiceTasks: [
            {
              id: 'pt-standard-2',
              prompt: 'Cho u_1 = 5, d = 4. Tính u_10 và S_10.',
              expectedAnswer: 'u_10 = 41, S_10 = 230.',
              hints: ['u_10 = 5 + 9 · 4.', 'S_10 = 10(5 + 41)/2.'],
              objectiveIds: ['obj-general-term', 'obj-sum-first-n'],
              difficulty: 'medium',
            },
          ],
        },
        {
          route: 'challenge',
          explanation: 'Ở tuyến thử thách, em sẽ xử lý bài toán ngược hoặc bài toán thực tế. Điều quan trọng là xác định đúng u_1, d, chỉ số n và đại lượng cần tìm là u_n hay S_n.',
          workedExamples: [
            {
              id: 'ex-challenge-2',
              title: 'Bài toán thực tế tiết kiệm',
              problem: 'Một học sinh tiết kiệm tháng đầu 100 nghìn đồng, mỗi tháng sau tăng thêm 20 nghìn đồng. Sau 6 tháng, bạn đó tiết kiệm được tổng cộng bao nhiêu?',
              solution: 'Mô hình hoá bài toán:\n\nu_1 = 100, d = 20, n = 6.\n\nTháng thứ 6 bạn tiết kiệm:\n\nu_6 = 100 + (6 - 1) · 20 = 200 nghìn đồng.\n\nTổng 6 tháng là:\n\nS_6 = 6(100 + 200)/2 = 900 nghìn đồng.',
              explanation: 'Câu hỏi “tổng cộng sau 6 tháng” yêu cầu S_6, không phải u_6. u_6 chỉ là số tiền của riêng tháng thứ 6.',
              objectiveIds: ['obj-sum-first-n', 'obj-context-ap'],
              timeLimitSeconds: 300,
              hintDelaySeconds: 120,
              hints: ['Hãy xác định u_1, d và n trước khi tính.', 'Câu hỏi hỏi “tổng cộng” nên cần tính S_6, nhưng em vẫn nên tìm u_6 trước để dùng công thức S_n = n(u_1 + u_n)/2.'],
              responseMode: 'image_upload',
              aiRubric: 'Chấm theo 4 ý: xác định đúng u_1 = 100, d = 20, n = 6; tính đúng u_6 = 200; dùng đúng công thức tổng S_6; kết luận có đơn vị nghìn đồng. Trừ nhẹ nếu thiếu đơn vị nhưng lập luận đúng.',
            },
          ],
          practiceTasks: [
            {
              id: 'pt-challenge-2',
              prompt: 'Một rạp có hàng đầu 12 ghế, mỗi hàng sau nhiều hơn hàng trước 2 ghế. Hàng thứ 10 có bao nhiêu ghế và 10 hàng đầu có bao nhiêu ghế?',
              expectedAnswer: 'u_10 = 30 ghế, S_10 = 210 ghế.',
              hints: ['u_1 = 12, d = 2.', 'Hỏi hàng thứ 10 là u_10; hỏi 10 hàng đầu là S_10.'],
              objectiveIds: ['obj-general-term', 'obj-sum-first-n', 'obj-context-ap'],
              difficulty: 'hard',
            },
          ],
        },
      ],
      quickCheck: {
        id: 'qc-unit-general-term-and-sum',
        title: 'Kiểm tra nhanh mảnh 2',
        purpose: 'quick_check',
        durationMinutes: 4,
        questions: [
          {
            id: 'qc3',
            type: 'multiple_choice',
            prompt: 'Cho cấp số cộng có u_1 = 6, d = 2. Số hạng u_7 bằng bao nhiêu?',
            options: ['18', '20', '14', '16'],
            correctAnswer: '18',
            explanation: 'u_7 = 6 + (7 - 1) · 2 = 18.',
            objectiveIds: ['obj-general-term'],
            misconceptionIds: ['mis-use-n-not-n-minus-1'],
            difficulty: 'medium',
            points: 1,
          },
          {
            id: 'qc4',
            type: 'multiple_choice',
            prompt: 'Cho u_1 = 2, u_6 = 17. Tổng S_6 bằng bao nhiêu?',
            options: ['57', '51', '19', '102'],
            correctAnswer: '57',
            explanation: 'S_6 = 6(2 + 17)/2 = 57.',
            objectiveIds: ['obj-sum-first-n'],
            misconceptionIds: ['mis-sum-vs-term'],
            difficulty: 'medium',
            points: 1,
          },
          {
            id: 'qc5',
            type: 'multiple_choice',
            prompt: 'Một người chạy ngày đầu 2 km, mỗi ngày sau tăng thêm 0,5 km. Ngày thứ 5 người đó chạy bao nhiêu km?',
            options: ['4 km', '4,5 km', '2,5 km', '10 km'],
            correctAnswer: '4 km',
            explanation: 'u_5 = 2 + (5 - 1) · 0,5 = 4 km.',
            objectiveIds: ['obj-context-ap', 'obj-general-term'],
            misconceptionIds: ['mis-context-index'],
            difficulty: 'hard',
            points: 1,
          },
        ],
      },
    },
  ],
  exitTicket: {
    id: 'exit-ap',
    title: 'Exit ticket — Cấp số cộng',
    purpose: 'exit_ticket',
    durationMinutes: 5,
    questions: [
      {
        id: 'exit1',
        type: 'multiple_choice',
        prompt: 'Để kiểm tra một dãy có phải cấp số cộng không, ta cần kiểm tra điều gì?',
        options: ['Hiệu hai số hạng liên tiếp có không đổi không', 'Tổng hai số hạng đầu', 'Tích hai số hạng liên tiếp', 'Dãy có tăng hay không'],
        correctAnswer: 'Hiệu hai số hạng liên tiếp có không đổi không',
        explanation: 'Cấp số cộng được nhận diện bằng hiệu u_{n+1} - u_n không đổi.',
        objectiveIds: ['obj-identify-ap'],
        difficulty: 'easy',
        points: 1,
      },
      {
        id: 'exit2',
        type: 'multiple_choice',
        prompt: 'Cho u_1 = 3, d = 4. Số hạng u_5 bằng bao nhiêu?',
        options: ['19', '23', '15', '20'],
        correctAnswer: '19',
        explanation: 'u_5 = 3 + (5 - 1) · 4 = 19.',
        objectiveIds: ['obj-general-term'],
        difficulty: 'medium',
        points: 1,
      },
      {
        id: 'exit3',
        type: 'multiple_choice',
        prompt: 'Nếu đề hỏi “tổng 10 số hạng đầu” thì đại lượng cần tính là gì?',
        options: ['S_10', 'u_10', 'd', 'u_1'],
        correctAnswer: 'S_10',
        explanation: 'Ký hiệu S_10 biểu thị tổng 10 số hạng đầu.',
        objectiveIds: ['obj-sum-first-n'],
        difficulty: 'easy',
        points: 1,
      },
    ],
  },
  completionReward: {
    toolId: 'gamedoikhang',
    message: 'Em đã học xong bài! Thử thách bạn cùng lớp trong Đấu Trường Tri Thức?',
  },
};
